// ─── SRD 5.2.1 Spell Import ──────────────────────────────────────
// Regenerates src/data/spells-*.ts from the 5etools 2024 Player's Handbook
// spell data, filtered to entries flagged srd52 (System Reference Document
// 5.2.1, CC-BY-4.0 — the legally redistributable subset). Class lists come
// from data/spells/sources.json, restricted to XPHB class spell lists.
//
//   npm run import:spells             # fetch from the pinned commit
//   npm run import:spells -- --local path/to/spells-xphb.json --local-sources path/to/sources.json
//
// The pinned SHA makes regeneration reproducible; generated files are
// committed, so builds never need the network. The audit gate fails loudly
// on converter drift instead of shipping garbage rules text. NOTE: the
// exact-count constants (EXPECTED_*) are facts of the pinned commit —
// bumping SOURCE_SHA means re-deriving them from the new data.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { import5eToolsSpells, synthesizeEffectSummary } from '../src/lib/import-5etools-spells';
import { SPELL_SUMMARY_OVERRIDES } from '../src/data/spell-summaries';
import type { FiveEToolsSpell } from '../src/lib/types';
import type { Spell } from '../src/data/spells';

const SOURCE_SHA = '3c5d9d3175ca9637132011c75efd73aad7a2364d'; // 5etools-src v2.32.1
const BASE_URL = `https://raw.githubusercontent.com/5etools-mirror-3/5etools-src/${SOURCE_SHA}/data/spells`;
const SPELLS_URL = `${BASE_URL}/spells-xphb.json`;
const SOURCES_URL = `${BASE_URL}/sources.json`;
const DATA_DIR = join(__dirname, '..', 'src', 'data');

const FILE_HEADER = `// AUTO-GENERATED by scripts/import-spells.ts — DO NOT EDIT BY HAND.
// Source: 5etools-src @ ${SOURCE_SHA.slice(0, 12)} (spells-xphb.json + spells/sources.json),
// filtered to entries in the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode
`;

// Facts of the pinned commit — re-derive when bumping SOURCE_SHA.
const EXPECTED_TOTAL = 339;
const EXPECTED_BY_LEVEL: Record<number, number> = { 0: 27, 1: 57, 2: 57, 3: 42, 4: 34, 5: 38, 6: 31, 7: 20, 8: 17, 9: 16 };
const EXPECTED_CONCENTRATION = 133;
const EXPECTED_RITUAL = 29;

const SRD_CLASSES = new Set(['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Warlock', 'Wizard']);

// Ids of the original hand-written spell reference (minus toll-the-dead,
// which is not SRD content). localStorage pins reference these — they must
// all survive the import.
const LEGACY_IDS = [
  'fire-bolt', 'eldritch-blast', 'sacred-flame', 'mage-hand', 'prestidigitation', 'guidance', 'light',
  'magic-missile', 'shield', 'healing-word', 'cure-wounds', 'detect-magic', 'thunderwave', 'sleep', 'command',
  'hold-person', 'misty-step', 'spiritual-weapon', 'scorching-ray',
  'fireball', 'lightning-bolt', 'counterspell', 'dispel-magic', 'spirit-guardians', 'revivify',
  'banishment', 'dimension-door', 'polymorph', 'wall-of-force', 'raise-dead',
  'disintegrate', 'wish', 'power-word-kill',
];

// Proper names WotC strips from SRD releases — none may survive a rename.
const NON_SRD_NAME_PATTERN = /Bigby|Tasha|Mordenkainen|Otiluke|Melf|Evard|Otto|Rary|Leomund|Nystul|Drawmij|Jallarzi|Yolande/;

const CASTING_TIME_PATTERN = /^(Action|Bonus Action|Reaction|\d+ (Minute|Minutes|Hour|Hours))$/;
const DURATION_PATTERN = /^(Instantaneous|Special|Permanent|Until dispelled( or triggered)?|(Up to )?\d+ (round|rounds|minute|minutes|hour|hours|day|days))( or .+)?$/;
const RANGE_PATTERN = /^(Touch|Self|Sight|Unlimited|Special|\d+ ft|\d+ miles?)$/;
const COMPONENTS_PATTERN = /^(V|S|M \(.+\))(, (V|S|M \(.+\)))*$/;
const SAVE_PATTERN = /^(STR|DEX|CON|INT|WIS|CHA)( or (STR|DEX|CON|INT|WIS|CHA))*$/;

interface Band {
  file: string;
  exportName: string;
  label: string;
  minLevel: number;
  maxLevel: number;
}

const BANDS: Band[] = [
  { file: 'spells-l0-1.ts', exportName: 'SPELLS_L0_1', label: 'Cantrips – 1st level', minLevel: 0, maxLevel: 1 },
  { file: 'spells-l2-3.ts', exportName: 'SPELLS_L2_3', label: '2nd – 3rd level', minLevel: 2, maxLevel: 3 },
  { file: 'spells-l4-5.ts', exportName: 'SPELLS_L4_5', label: '4th – 5th level', minLevel: 4, maxLevel: 5 },
  { file: 'spells-l6-9.ts', exportName: 'SPELLS_L6_9', label: '6th – 9th level', minLevel: 6, maxLevel: 9 },
];

interface SourcesJson {
  XPHB?: Record<string, { class?: Array<{ name: string; source: string }> }>;
}

async function obtainJson<T>(url: string, localFlag: string): Promise<T> {
  const flagIndex = process.argv.indexOf(localFlag);
  if (flagIndex !== -1) {
    const path = process.argv[flagIndex + 1];
    if (!path) throw new Error(`${localFlag} requires a file path`);
    console.log(`Reading local file: ${path}`);
    return JSON.parse(readFileSync(path, 'utf-8')) as T;
  }
  console.log(`Fetching ${url}`);
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Fetch failed (${res.status}). If the mirror moved, download the file manually and use ${localFlag}.`);
  }
  return (await res.json()) as T;
}

interface AuditFailure {
  spell: string;
  problem: string;
}

function audit(spells: Spell[], rawByName: Map<string, FiveEToolsSpell>): AuditFailure[] {
  const failures: AuditFailure[] = [];
  const fail = (spell: string, problem: string) => failures.push({ spell, problem });

  // Corpus-level counts
  if (spells.length !== EXPECTED_TOTAL) fail('(aggregate)', `total ${spells.length} !== ${EXPECTED_TOTAL}`);
  for (const [level, expected] of Object.entries(EXPECTED_BY_LEVEL)) {
    const actual = spells.filter((s) => s.level === Number(level)).length;
    if (actual !== expected) fail('(aggregate)', `level ${level}: ${actual} !== ${expected}`);
  }
  const conc = spells.filter((s) => s.concentration).length;
  if (conc !== EXPECTED_CONCENTRATION) fail('(aggregate)', `concentration ${conc} !== ${EXPECTED_CONCENTRATION}`);
  const ritual = spells.filter((s) => s.ritual).length;
  if (ritual !== EXPECTED_RITUAL) fail('(aggregate)', `ritual ${ritual} !== ${EXPECTED_RITUAL}`);

  // Uniqueness + legacy-id continuity + licensing
  const ids = new Set<string>();
  const names = new Set<string>();
  for (const s of spells) {
    if (ids.has(s.id)) fail(s.name, `duplicate id ${s.id}`);
    if (names.has(s.name)) fail(s.name, 'duplicate name');
    ids.add(s.id);
    names.add(s.name);
  }
  for (const legacyId of LEGACY_IDS) {
    if (!ids.has(legacyId)) fail('(aggregate)', `legacy id missing: ${legacyId} (breaks saved pins)`);
  }
  if (ids.has('toll-the-dead')) fail('Toll the Dead', 'non-SRD spell must not ship');
  for (const s of spells) {
    if (NON_SRD_NAME_PATTERN.test(s.name)) fail(s.name, 'proper-named spell shipped without SRD rename');
  }

  // Per-spell integrity
  const rawReactions = new Set(
    [...rawByName.entries()].filter(([, r]) => r.time[0]?.unit === 'reaction').map(([n]) => n),
  );
  const rawTables = new Set(
    [...rawByName.entries()].filter(([, r]) => JSON.stringify(r.entries).includes('"type":"table"')).map(([n]) => n),
  );
  for (const s of spells) {
    const serialized = JSON.stringify(s);
    if (serialized.includes('{@')) {
      const residue = serialized.match(/\{@\w+[^}]*\}/g)?.slice(0, 3).join(' ');
      fail(s.name, `unstripped tag(s): ${residue}`);
    }
    if (serialized.includes('[object Object]')) fail(s.name, 'unflattened entry ([object Object])');

    if (!CASTING_TIME_PATTERN.test(s.castingTime)) fail(s.name, `castingTime '${s.castingTime}'`);
    if (!DURATION_PATTERN.test(s.duration)) fail(s.name, `duration '${s.duration}'`);
    if (!RANGE_PATTERN.test(s.range)) fail(s.name, `range '${s.range}'`);
    if (!COMPONENTS_PATTERN.test(s.components)) fail(s.name, `components '${s.components}'`);
    if (s.saveType && !SAVE_PATTERN.test(s.saveType)) fail(s.name, `saveType '${s.saveType}'`);

    if (s.classes.length === 0) fail(s.name, 'no classes');
    for (const c of s.classes) {
      if (!SRD_CLASSES.has(c)) fail(s.name, `non-SRD class '${c}'`);
    }

    // 2024 SRD has legitimately terse spells (False Life is one sentence);
    // this only catches empty/mangled conversions.
    if (s.description.length < 30) fail(s.name, `description too short (${s.description.length})`);
    if (rawReactions.has(s.name) && !s.description.startsWith('Trigger: ')) {
      fail(s.name, 'reaction spell missing Trigger lead paragraph');
    }
    if (rawTables.has(s.name) && !(s.description.includes('\n') && s.description.includes(': '))) {
      fail(s.name, 'table spell emitted no table rows');
    }

    if (s.effectSummary.length === 0) fail(s.name, 'empty effectSummary');
    if (s.effectSummary.length > 200) fail(s.name, `effectSummary too long (${s.effectSummary.length})`);
  }

  // Coverage parity: every raw structured field must survive conversion.
  const rawWith = (pred: (r: FiveEToolsSpell) => boolean) => [...rawByName.values()].filter(pred).length;
  const parity: Array<[string, number, number]> = [
    ['upcast', rawWith((r) => (r.entriesHigherLevel?.length ?? 0) > 0), spells.filter((s) => s.upcast).length],
    ['saveType', rawWith((r) => (r.savingThrow?.length ?? 0) > 0), spells.filter((s) => s.saveType).length],
    ['attackType', rawWith((r) => (r.spellAttack?.length ?? 0) > 0), spells.filter((s) => s.attackType).length],
    ['damageType', rawWith((r) => (r.damageInflict?.length ?? 0) > 0), spells.filter((s) => s.damageType).length],
  ];
  for (const [field, raw, converted] of parity) {
    if (raw !== converted) fail('(aggregate)', `${field} coverage: raw ${raw} !== converted ${converted}`);
  }

  return failures;
}

function emitBandFile(band: Band, spells: Spell[]): void {
  const body = JSON.stringify(spells, null, 2);
  const content = `${FILE_HEADER}
import type { Spell } from './spells';

// ${band.label} — ${spells.length} spells
export const ${band.exportName}: Spell[] = ${body};
`;
  writeFileSync(join(DATA_DIR, band.file), content, 'utf-8');
  console.log(`  ${band.file}: ${spells.length} spells (${band.label})`);
}

async function main(): Promise<void> {
  const spellsJson = await obtainJson<{ spell: FiveEToolsSpell[] }>(SPELLS_URL, '--local');
  const sourcesJson = await obtainJson<SourcesJson>(SOURCES_URL, '--local-sources');
  console.log(`Total spells in source: ${spellsJson.spell.length}`);

  const srdEntries = spellsJson.spell.filter(
    (s) => s.srd52 === true || typeof s.srd52 === 'string',
  );
  console.log(`SRD 5.2.1 entries: ${srdEntries.length}`);

  const copyUsers = srdEntries.filter((s) => '_copy' in s && s._copy !== undefined);
  if (copyUsers.length > 0) {
    throw new Error(`_copy inheritance is not supported; offending entries: ${copyUsers.map((s) => s.name).join(', ')}`);
  }

  const classesByOriginalName = new Map<string, string[]>();
  for (const [name, entry] of Object.entries(sourcesJson.XPHB ?? {})) {
    classesByOriginalName.set(
      name,
      (entry.class ?? []).filter((c) => c.source === 'XPHB').map((c) => c.name),
    );
  }

  const converted = import5eToolsSpells({ spell: srdEntries }, {
    source: 'SRD 5.2.1',
    classesByOriginalName,
    summaryOverrides: SPELL_SUMMARY_OVERRIDES,
  });
  converted.sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));

  const rawByName = new Map(
    srdEntries.map((s) => [typeof s.srd52 === 'string' ? s.srd52 : s.name, s]),
  );
  const failures = audit(converted, rawByName);
  if (failures.length > 0) {
    console.error(`\nAUDIT FAILED — ${failures.length} problem(s):`);
    for (const f of failures.slice(0, 25)) {
      console.error(`  ${f.spell}: ${f.problem}`);
    }
    if (failures.length > 25) console.error(`  ...and ${failures.length - 25} more`);
    process.exit(1);
  }
  console.log('Audit passed.');

  // Curation progress: how each effectSummary was produced.
  let overridden = 0;
  let synthesized = 0;
  let firstSentence = 0;
  for (const s of converted) {
    if (SPELL_SUMMARY_OVERRIDES[s.id]) { overridden++; continue; }
    const raw = rawByName.get(s.name)!;
    if (synthesizeEffectSummary(raw, s, s.description)) synthesized++;
    else firstSentence++;
  }
  console.log(`Summaries: ${overridden} curated, ${synthesized} synthesized, ${firstSentence} first-sentence.`);

  console.log('\nWriting data files:');
  for (const band of BANDS) {
    emitBandFile(band, converted.filter((s) => s.level >= band.minLevel && s.level <= band.maxLevel));
  }

  const meta = `${FILE_HEADER}
export const SPELLS_META = {
  count: ${converted.length},
  source: 'SRD 5.2.1',
  license: 'CC-BY-4.0',
  sourceCommit: '${SOURCE_SHA}',
} as const;
`;
  writeFileSync(join(DATA_DIR, 'spells-meta.ts'), meta, 'utf-8');
  console.log(`  spells-meta.ts: count=${converted.length}`);

  const byLevel = new Map<number, number>();
  for (const s of converted) byLevel.set(s.level, (byLevel.get(s.level) ?? 0) + 1);
  const levels = Array.from(byLevel.keys()).sort((a, b) => a - b);
  console.log(`\nLevel coverage: ${levels.map((l) => `L${l}×${byLevel.get(l)}`).join(', ')}`);
  console.log(`\nDone — ${converted.length} SRD 5.2.1 spells imported.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
