// Regenerates the structured SRD 5.2.1 content missing from the original app.
// Inputs are the per-entry Markdown files in SRD-reForged at a pinned commit.
// Generated TypeScript is committed, so builds and CI never require network.
//
//   npm run import:srd
//   npm run import:srd -- --local path/to/dnd.srd.5.2.1

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import type {
  Background,
  Feat,
  MagicItem,
  MagicItemRarity,
  Species,
  SrdClassEntry,
  SrdEquipmentItem,
  SrdReferenceArticle,
} from '../src/lib/srd-content-types';
import { convertBackground, convertFeat, convertMagicItem, convertSpecies } from './srd-md/convert';
import {
  convertAdventuringGear,
  convertChapterArticles,
  convertClassFile,
  convertEquipmentTables,
  convertRuleEntry,
  convertTool,
} from './srd-md/convert-reference';
import {
  SRD_REFORGED_REPOSITORY,
  SRD_REFORGED_SHA,
  SRD_SOURCE_DIRS,
  SRD_SOURCE_FILES,
} from './srd-md/source';

const DATA_DIR = resolve(__dirname, '..', 'src', 'data');
const EXPECTED_COUNTS = {
  rules: 200,
  classes: 24,
  equipment: 182,
  magicItems: 257,
  feats: 17,
  backgrounds: 4,
  species: 9,
} as const;

const FILE_HEADER = `// AUTO-GENERATED by scripts/import-srd-content.ts — DO NOT EDIT BY HAND.
// Source: https://github.com/${SRD_REFORGED_REPOSITORY} @ ${SRD_REFORGED_SHA.slice(0, 12)},
// transcribed from the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode
`;

interface SourceFile {
  path: string;
  markdown: string;
}

let remoteTreePromise: Promise<Array<{ path: string; type: string }>> | undefined;

async function remoteTree(): Promise<Array<{ path: string; type: string }>> {
  if (remoteTreePromise) return remoteTreePromise;
  const treeUrl = `https://api.github.com/repos/${SRD_REFORGED_REPOSITORY}/git/trees/${SRD_REFORGED_SHA}?recursive=1`;
  remoteTreePromise = (async () => {
    const response = await fetch(treeUrl, { headers: { Accept: 'application/vnd.github+json' } });
    if (!response.ok) throw new Error(`Unable to list SRD source tree (${response.status}).`);
    return (await response.json() as { tree: Array<{ path: string; type: string }> }).tree;
  })();
  return remoteTreePromise;
}

async function fetchRemoteFile(path: string): Promise<SourceFile> {
  const rawUrl = `https://raw.githubusercontent.com/${SRD_REFORGED_REPOSITORY}/${SRD_REFORGED_SHA}/${path}`;
  const response = await fetch(rawUrl);
  if (!response.ok) throw new Error(`Unable to fetch ${path} (${response.status}).`);
  return { path, markdown: await response.text() };
}

async function fetchRemoteFiles(directory: string): Promise<SourceFile[]> {
  const paths = (await remoteTree())
    .filter((entry) => entry.type === 'blob' && entry.path.startsWith(`${directory}/`) && entry.path.endsWith('.md'))
    .map((entry) => entry.path)
    .sort();

  const files: SourceFile[] = [];
  for (let offset = 0; offset < paths.length; offset += 12) {
    const batch = paths.slice(offset, offset + 12);
    files.push(...await Promise.all(batch.map(fetchRemoteFile)));
  }
  return files;
}

function readLocalFiles(root: string, directory: string): SourceFile[] {
  const nativeDirectory = join(root, ...directory.split('/'));
  return readdirSync(nativeDirectory, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
    .map((entry) => {
      const filePath = join(nativeDirectory, entry.name);
      return {
        path: relative(root, filePath).replace(/\\/g, '/'),
        markdown: readFileSync(filePath, 'utf8'),
      };
    })
    .sort((a, b) => a.path.localeCompare(b.path));
}

async function sourceFiles(directory: string): Promise<SourceFile[]> {
  const localIndex = process.argv.indexOf('--local');
  if (localIndex === -1) return fetchRemoteFiles(directory);
  const localRoot = process.argv[localIndex + 1];
  if (!localRoot) throw new Error('--local requires the SRD-reForged checkout path.');
  return readLocalFiles(resolve(localRoot), directory);
}

async function sourceFile(path: string): Promise<SourceFile> {
  const localIndex = process.argv.indexOf('--local');
  if (localIndex === -1) return fetchRemoteFile(path);
  const localRoot = process.argv[localIndex + 1];
  if (!localRoot) throw new Error('--local requires the SRD-reForged checkout path.');
  const resolvedRoot = resolve(localRoot);
  const nativePath = join(resolvedRoot, ...path.split('/'));
  return { path, markdown: readFileSync(nativePath, 'utf8') };
}

function assertCount(label: keyof typeof EXPECTED_COUNTS, actual: number): void {
  const expected = EXPECTED_COUNTS[label];
  if (actual !== expected) throw new Error(`${label}: ${actual} entries; expected ${expected}.`);
}

function sortByName<T extends { name: string }>(values: T[]): T[] {
  return values.sort((a, b) => a.name.localeCompare(b.name));
}

function emit(file: string, type: string, exportName: string, values: unknown[]): void {
  const content = `${FILE_HEADER}\nimport type { ${type} } from '../lib/srd-content-types';\n\nexport const ${exportName}: ${type}[] = ${JSON.stringify(values, null, 2)};\n`;
  writeFileSync(join(DATA_DIR, file), content, 'utf8');
  console.log(`  ${file}: ${values.length}`);
}

function emitMeta(file: string, exportName: string, count: number): void {
  const content = `${FILE_HEADER}\nimport type { SrdContentMeta } from '../lib/srd-content-types';\n\nexport const ${exportName}: SrdContentMeta = {\n  count: ${count},\n  source: 'SRD 5.2.1',\n  license: 'CC-BY-4.0',\n  sourceRepository: '${SRD_REFORGED_REPOSITORY}',\n  sourceCommit: '${SRD_REFORGED_SHA}',\n};\n`;
  writeFileSync(join(DATA_DIR, file), content, 'utf8');
}

function emitReferenceMeta(rules: number, classes: number, equipment: number): void {
  const content = `${FILE_HEADER}\nimport type { SrdReferenceContentMeta } from '../lib/srd-content-types';\n\nexport const REFERENCE_CONTENT_META: SrdReferenceContentMeta = {\n  rules: ${rules},\n  classes: ${classes},\n  equipment: ${equipment},\n  source: 'SRD 5.2.1',\n  license: 'CC-BY-4.0',\n  sourceRepository: '${SRD_REFORGED_REPOSITORY}',\n  sourceCommit: '${SRD_REFORGED_SHA}',\n};\n`;
  writeFileSync(join(DATA_DIR, 'reference-content-meta.ts'), content, 'utf8');
}

const RARITY_RANK: Record<MagicItemRarity, number> = {
  Common: 0,
  Uncommon: 1,
  Rare: 2,
  'Very Rare': 3,
  Legendary: 4,
  Artifact: 5,
  Varies: 6,
};

function itemBand(item: MagicItem): 'common-uncommon' | 'rare' | 'very-rare' | 'legendary-artifact' | 'varies' {
  if (item.rarities.includes('Varies')) return 'varies';
  const rank = Math.min(...item.rarities.map((rarity) => RARITY_RANK[rarity]));
  if (rank <= 1) return 'common-uncommon';
  if (rank === 2) return 'rare';
  if (rank === 3) return 'very-rare';
  return 'legendary-artifact';
}

async function main(): Promise<void> {
  mkdirSync(DATA_DIR, { recursive: true });
  const [
    classSources,
    magicSources,
    featSources,
    backgroundSources,
    speciesSources,
    gearSources,
    toolSources,
    glossarySources,
    playingSource,
    characterCreationSource,
    equipmentSource,
    spellRulesSource,
    toolboxSource,
    magicItemRulesSource,
  ] = await Promise.all([
    sourceFiles(SRD_SOURCE_DIRS.classes),
    sourceFiles(SRD_SOURCE_DIRS.magicItems),
    sourceFiles(SRD_SOURCE_DIRS.feats),
    sourceFiles(SRD_SOURCE_DIRS.backgrounds),
    sourceFiles(SRD_SOURCE_DIRS.species),
    sourceFiles(SRD_SOURCE_DIRS.adventuringGear),
    sourceFiles(SRD_SOURCE_DIRS.tools),
    sourceFiles(SRD_SOURCE_DIRS.rulesGlossary),
    sourceFile(SRD_SOURCE_FILES.playingTheGame),
    sourceFile(SRD_SOURCE_FILES.characterCreation),
    sourceFile(SRD_SOURCE_FILES.equipment),
    sourceFile(SRD_SOURCE_FILES.spells),
    sourceFile(SRD_SOURCE_FILES.gameplayToolbox),
    sourceFile(SRD_SOURCE_FILES.magicItems),
  ]);

  const classes = sortByName(classSources.flatMap(({ markdown }) => convertClassFile(markdown)) as SrdClassEntry[]);
  const magicItems = sortByName(magicSources.map(({ path, markdown }) => convertMagicItem(path, markdown)));
  const feats = sortByName(featSources.map(({ path, markdown }) => convertFeat(path, markdown)));
  const backgrounds = sortByName(backgroundSources.map(({ path, markdown }) => convertBackground(path, markdown)));
  const species = sortByName(speciesSources.map(({ path, markdown }) => convertSpecies(path, markdown)));
  const rules = sortByName([
    ...convertChapterArticles(playingSource.markdown, 'Playing the Game'),
    ...convertChapterArticles(characterCreationSource.markdown, 'Character Creation'),
    ...convertChapterArticles(equipmentSource.markdown, 'Equipment Rules'),
    ...convertChapterArticles(spellRulesSource.markdown, 'Spellcasting Rules', ['Spell Descriptions']),
    ...glossarySources.map(({ markdown }) => convertRuleEntry(markdown)),
    ...convertChapterArticles(toolboxSource.markdown, 'Gameplay Toolbox'),
    ...convertChapterArticles(magicItemRulesSource.markdown, 'Magic Item Rules', ['Magic Items A-Z']),
  ] as SrdReferenceArticle[]);
  const equipment = sortByName([
    ...convertEquipmentTables(equipmentSource.markdown),
    ...gearSources.map(({ markdown }) => convertAdventuringGear(markdown, equipmentSource.markdown)),
    ...toolSources.map(({ markdown }) => convertTool(markdown)),
  ] as SrdEquipmentItem[]);

  assertCount('rules', rules.length);
  assertCount('classes', classes.length);
  assertCount('equipment', equipment.length);
  assertCount('magicItems', magicItems.length);
  assertCount('feats', feats.length);
  assertCount('backgrounds', backgrounds.length);
  assertCount('species', species.length);

  console.log('Writing generated SRD content:');
  emit('reference-articles.ts', 'SrdReferenceArticle', 'SRD_REFERENCE_ARTICLES', rules);
  emit('classes.ts', 'SrdClassEntry', 'SRD_CLASSES', classes);
  emit('equipment.ts', 'SrdEquipmentItem', 'SRD_EQUIPMENT', equipment);
  const bands = [
    ['common-uncommon', 'MAGIC_ITEMS_COMMON_UNCOMMON'],
    ['rare', 'MAGIC_ITEMS_RARE'],
    ['very-rare', 'MAGIC_ITEMS_VERY_RARE'],
    ['legendary-artifact', 'MAGIC_ITEMS_LEGENDARY_ARTIFACT'],
    ['varies', 'MAGIC_ITEMS_VARIES'],
  ] as const;
  for (const [band, exportName] of bands) {
    emit(`magic-items-${band}.ts`, 'MagicItem', exportName, magicItems.filter((item) => itemBand(item) === band));
  }
  emit('feats.ts', 'Feat', 'FEATS', feats);
  emit('backgrounds.ts', 'Background', 'BACKGROUNDS', backgrounds);
  emit('species.ts', 'Species', 'SPECIES', species);
  emitMeta('magic-items-meta.ts', 'MAGIC_ITEMS_META', magicItems.length);
  emitMeta('feats-meta.ts', 'FEATS_META', feats.length);
  emitMeta('origins-meta.ts', 'ORIGINS_META', backgrounds.length + species.length);
  emitReferenceMeta(rules.length, classes.length, equipment.length);

  console.log(
    `Done — ${rules.length} rules, ${classes.length} classes/subclasses, ${equipment.length} equipment entries, `
      + `${magicItems.length} magic items, ${feats.length} feats, ${backgrounds.length} backgrounds, ${species.length} species.`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
