// AUTO-GENERATED by scripts/import-srd-content.ts — DO NOT EDIT BY HAND.
// Source: https://github.com/oldmanumby/dnd.srd.5.2.1 @ af537072cc95,
// transcribed from the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode

import type { Background } from '../lib/srd-content-types';

export const BACKGROUNDS: Background[] = [
  {
    "id": "acolyte",
    "name": "Acolyte",
    "abilityScores": [
      "Intelligence",
      "Wisdom",
      "Charisma"
    ],
    "feat": "Magic Initiate (Cleric)",
    "skillProficiencies": [
      "Insight",
      "Religion"
    ],
    "toolProficiency": "Calligrapher's Supplies",
    "equipment": "Choose A or B: (A) Calligrapher's Supplies, Book (prayers), Holy Symbol, Parchment (10 sheets), Robe, 8 GP; or (B) 50 GP",
    "description": "",
    "source": "SRD 5.2.1"
  },
  {
    "id": "criminal",
    "name": "Criminal",
    "abilityScores": [
      "Dexterity",
      "Constitution",
      "Intelligence"
    ],
    "feat": "Alert",
    "skillProficiencies": [
      "Sleight of Hand",
      "Stealth"
    ],
    "toolProficiency": "Thieves' Tools",
    "equipment": "Choose A or B: (A) 2 Daggers, Thieves' Tools, Crowbar, 2 Pouches, Traveler's Clothes, 16 GP; or (B) 50 GP",
    "description": "",
    "source": "SRD 5.2.1"
  },
  {
    "id": "sage",
    "name": "Sage",
    "abilityScores": [
      "Constitution",
      "Intelligence",
      "Wisdom"
    ],
    "feat": "Magic Initiate (Wizard)",
    "skillProficiencies": [
      "Arcana",
      "History"
    ],
    "toolProficiency": "Calligrapher's Supplies",
    "equipment": "Choose A or B: (A) Quarterstaff, Calligrapher's Supplies, Book (history), Parchment (8 sheets), Robe, 8 GP; or (B) 50 GP",
    "description": "",
    "source": "SRD 5.2.1"
  },
  {
    "id": "soldier",
    "name": "Soldier",
    "abilityScores": [
      "Strength",
      "Dexterity",
      "Constitution"
    ],
    "feat": "Savage Attacker",
    "skillProficiencies": [
      "Athletics",
      "Intimidation"
    ],
    "toolProficiency": "Choose one kind of Gaming Set (see \"Equipment\")",
    "equipment": "Choose A or B: (A) Spear, Shortbow, 20 Arrows, Gaming Set (same as above), Healer's Kit, Quiver, Traveler's Clothes, 14 GP; or (B) 50 GP",
    "description": "",
    "source": "SRD 5.2.1"
  }
];
