// AUTO-GENERATED by scripts/import-bestiary.ts — DO NOT EDIT BY HAND.
// Source: 5etools-src @ 3c5d9d3175ca (bestiary-xmm.json),
// filtered to entries in the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode

export const BESTIARY_META = {
  count: 331,
  creatureTypes: 14,
  source: 'SRD 5.2.1',
  license: 'CC-BY-4.0',
  sourceCommit: '3c5d9d3175ca9637132011c75efd73aad7a2364d',
} as const;
