// AUTO-GENERATED by scripts/import-bestiary.ts — DO NOT EDIT BY HAND.
// Source: 5etools-src @ 974d5bfb7cea (bestiary-xmm.json),
// filtered to entries in the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode

export const BESTIARY_META = {
  count: 331,
  source: 'SRD 5.2.1',
  license: 'CC-BY-4.0',
  sourceCommit: '974d5bfb7ceae1a13c0213d9b73d9692bd28ca49',
} as const;
