// AUTO-GENERATED by scripts/import-bestiary.ts — DO NOT EDIT BY HAND.
// Source: 5etools-src @ 3c5d9d3175ca (bestiary-xmm.json),
// filtered to entries in the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode

import { Monster } from '../lib/types';

// CR 9 – 13 — 29 monsters
export const MONSTERS_CR_9_13: Monster[] = [
  {
    "id": "bone-devil",
    "name": "Bone Devil",
    "source": "SRD52",
    "size": "Large",
    "type": "Fiend",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 16
    },
    "hitPoints": 161,
    "hitDice": "17d10 + 68",
    "speed": {
      "walk": 40,
      "fly": 40
    },
    "abilities": {
      "str": 18,
      "dex": 16,
      "con": 18,
      "int": 13,
      "wis": 14,
      "cha": 16
    },
    "senses": [
      "Darkvision 120 ft. (unimpeded by magical Darkness)",
      "passive Perception 12"
    ],
    "languages": [
      "Infernal; telepathy 120 ft."
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Cold"
    ],
    "damageImmunities": [
      "Fire",
      "Poison"
    ],
    "conditionImmunities": [
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The devil makes two Claw attacks and one Infernal Sting attack."
      },
      {
        "name": "Claw",
        "description": "Melee Attack Roll: +8, reach 10 ft. Hit: 13 (2d8 + 4) Slashing damage.",
        "attackDelivery": "Melee",
        "attackBonus": 8,
        "reach": 10,
        "damageTypes": [
          "Slashing"
        ],
        "damageDice": "2d8+4",
        "damageAvg": 13
      },
      {
        "name": "Infernal Sting",
        "description": "Melee Attack Roll: +8, reach 10 ft. Hit: 15 (2d10 + 4) Piercing damage plus 18 (4d8) Poison damage, and the target has the Poisoned condition until the start of the devil's next turn. While Poisoned, the target can't regain Hit Points.",
        "attackDelivery": "Melee",
        "attackBonus": 8,
        "reach": 10,
        "damageTypes": [
          "Piercing",
          "Poison"
        ],
        "damageDice": "2d10+4",
        "damageAvg": 15
      }
    ],
    "environments": [
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Slashing",
      "Piercing",
      "Poison"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "magic resistance",
      "flyer"
    ],
    "subtype": "devil",
    "savingThrows": {
      "str": 8,
      "int": 5,
      "wis": 6,
      "cha": 7
    },
    "skills": {
      "Deception": 7,
      "Insight": 6
    },
    "specialAbilities": [
      {
        "name": "Diabolical Restoration",
        "description": "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells."
      },
      {
        "name": "Magic Resistance",
        "description": "The devil has Advantage on saving throws against spells and other magical effects."
      }
    ]
  },
  {
    "id": "clay-golem",
    "name": "Clay Golem",
    "source": "SRD52",
    "size": "Large",
    "type": "Construct",
    "alignment": "Unaligned",
    "armor": {
      "ac": 14
    },
    "hitPoints": 123,
    "hitDice": "13d10 + 52",
    "speed": {
      "walk": 20
    },
    "abilities": {
      "str": 20,
      "dex": 9,
      "con": 18,
      "int": 3,
      "wis": 8,
      "cha": 1
    },
    "senses": [
      "Darkvision 60 ft.",
      "passive Perception 9"
    ],
    "languages": [
      "Common plus one other language"
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Bludgeoning",
      "Piercing",
      "Slashing"
    ],
    "damageImmunities": [
      "Acid",
      "Poison",
      "Psychic"
    ],
    "conditionImmunities": [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Petrified",
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The golem makes two Slam attacks, or it makes three Slam attacks if it used Hasten this turn."
      },
      {
        "name": "Slam",
        "description": "Melee Attack Roll: +9, reach 5 ft. Hit: 10 (1d10 + 5) Bludgeoning damage plus 6 (1d12) Acid damage, and the target's Hit Point maximum decreases by an amount equal to the Acid damage taken.",
        "attackDelivery": "Melee",
        "attackBonus": 9,
        "reach": 5,
        "damageTypes": [
          "Acid",
          "Bludgeoning"
        ],
        "damageDice": "1d10+5",
        "damageAvg": 10
      }
    ],
    "environments": [
      "Urban"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Acid",
      "Bludgeoning"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "magic resistance"
    ],
    "specialAbilities": [
      {
        "name": "Acid Absorption",
        "description": "Whenever the golem is subjected to Acid damage, it takes no damage and instead regains a number of Hit Points equal to the Acid damage dealt.",
        "damageTypes": [
          "Acid"
        ]
      },
      {
        "name": "Berserk",
        "description": "Whenever the golem starts its turn Bloodied, roll 1d6. On a 6, the golem goes berserk. On each of its turns while berserk, the golem attacks the nearest creature it can see. If no creature is near enough to move to and attack, the golem attacks an object. Once the golem goes berserk, it continues to be berserk until it is destroyed or it is no longer Bloodied."
      },
      {
        "name": "Immutable Form",
        "description": "The golem can't shape-shift."
      },
      {
        "name": "Magic Resistance",
        "description": "The golem has Advantage on saving throws against spells and other magical effects."
      }
    ],
    "bonusActions": [
      {
        "name": "Hasten (Recharge 5–6)",
        "description": "The golem takes the Dash and Disengage actions."
      }
    ]
  },
  {
    "id": "cloud-giant",
    "name": "Cloud Giant",
    "source": "SRD52",
    "size": "Huge",
    "type": "Giant",
    "alignment": "True Neutral",
    "armor": {
      "ac": 14
    },
    "hitPoints": 200,
    "hitDice": "16d12 + 96",
    "speed": {
      "walk": 40,
      "fly": 20,
      "hover": true
    },
    "abilities": {
      "str": 27,
      "dex": 10,
      "con": 22,
      "int": 12,
      "wis": 16,
      "cha": 16
    },
    "senses": [
      "passive Perception 21"
    ],
    "languages": [
      "Common",
      "Giant"
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The giant makes two attacks, using Thunderous Mace or Thundercloud in any combination. It can replace one attack with a use of Spellcasting to cast Fog Cloud.",
        "damageTypes": [
          "Thunder"
        ]
      },
      {
        "name": "Thunderous Mace",
        "description": "Melee Attack Roll: +12, reach 10 ft. Hit: 21 (3d8 + 8) Bludgeoning damage plus 7 (2d6) Thunder damage.",
        "attackDelivery": "Melee",
        "attackBonus": 12,
        "reach": 10,
        "damageTypes": [
          "Bludgeoning",
          "Thunder"
        ],
        "damageDice": "3d8+8",
        "damageAvg": 21
      },
      {
        "name": "Thundercloud",
        "description": "Ranged Attack Roll: +12, range 240 ft. Hit: 18 (3d6 + 8) Thunder damage, and the target has the Incapacitated condition until the end of its next turn.",
        "attackDelivery": "Ranged",
        "attackBonus": 12,
        "range": 240,
        "damageTypes": [
          "Thunder"
        ],
        "damageDice": "3d6+8",
        "damageAvg": 18
      }
    ],
    "environments": [
      "Mountain"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Hover"
    ],
    "attackDamageTypes": [
      "Thunder",
      "Bludgeoning"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "flyer"
    ],
    "savingThrows": {
      "con": 10,
      "wis": 7
    },
    "skills": {
      "Insight": 7,
      "Perception": 11
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 15,
      "atWill": [
        "Detect Magic",
        "Fog Cloud",
        "Light"
      ],
      "perDay": {
        "1": [
          "Control Weather",
          "Gaseous Form",
          "Telekinesis"
        ]
      }
    }
  },
  {
    "id": "fire-giant",
    "name": "Fire Giant",
    "source": "SRD52",
    "size": "Huge",
    "type": "Giant",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 162,
    "hitDice": "13d12 + 78",
    "speed": {
      "walk": 30
    },
    "abilities": {
      "str": 25,
      "dex": 9,
      "con": 23,
      "int": 10,
      "wis": 14,
      "cha": 13
    },
    "senses": [
      "passive Perception 16"
    ],
    "languages": [
      "Giant"
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The giant makes two attacks, using Flame Sword or Hammer Throw in any combination."
      },
      {
        "name": "Flame Sword",
        "description": "Melee Attack Roll: +11, reach 10 ft. Hit: 21 (4d6 + 7) Slashing damage plus 10 (3d6) Fire damage.",
        "attackDelivery": "Melee",
        "attackBonus": 11,
        "reach": 10,
        "damageTypes": [
          "Fire",
          "Slashing"
        ],
        "damageDice": "4d6+7",
        "damageAvg": 21
      },
      {
        "name": "Hammer Throw",
        "description": "Ranged Attack Roll: +11, range 60/240 ft. Hit: 23 (3d10 + 7) Bludgeoning damage plus 4 (1d8) Fire damage, and the target is pushed up to 15 feet straight away from the giant and has Disadvantage on the next attack roll it makes before the end of its next turn.",
        "attackDelivery": "Ranged",
        "attackBonus": 11,
        "range": 60,
        "longRange": 240,
        "damageTypes": [
          "Bludgeoning",
          "Fire"
        ],
        "damageDice": "3d10+7",
        "damageAvg": 23
      }
    ],
    "environments": [
      "Mountain",
      "Underdark"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Fire",
      "Slashing",
      "Bludgeoning"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack"
    ],
    "savingThrows": {
      "dex": 3,
      "con": 10,
      "cha": 5
    },
    "skills": {
      "Athletics": 11,
      "Perception": 6
    }
  },
  {
    "id": "glabrezu",
    "name": "Glabrezu",
    "source": "SRD52",
    "size": "Large",
    "type": "Fiend",
    "alignment": "Chaotic Evil",
    "armor": {
      "ac": 17
    },
    "hitPoints": 189,
    "hitDice": "18d10 + 90",
    "speed": {
      "walk": 40
    },
    "abilities": {
      "str": 20,
      "dex": 15,
      "con": 21,
      "int": 19,
      "wis": 17,
      "cha": 16
    },
    "senses": [
      "Truesight 120 ft.",
      "passive Perception 17"
    ],
    "languages": [
      "Abyssal; telepathy 120 ft."
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Cold",
      "Fire",
      "Lightning"
    ],
    "damageImmunities": [
      "Poison"
    ],
    "conditionImmunities": [
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The glabrezu makes two Pincer attacks and uses Pummel or Spellcasting."
      },
      {
        "name": "Pincer",
        "description": "Melee Attack Roll: +9, reach 10 ft. Hit: 16 (2d10 + 5) Slashing damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 15) from one of two pincers.",
        "attackDelivery": "Melee",
        "attackBonus": 9,
        "reach": 10,
        "damageTypes": [
          "Slashing"
        ],
        "damageDice": "2d10+5",
        "damageAvg": 16
      },
      {
        "name": "Pummel",
        "description": "Dexterity Saving Throw: DC 17, one creature Grappled by the glabrezu. Failure: 15 (3d6 + 5) Bludgeoning damage. Success: Half damage.",
        "damageTypes": [
          "Bludgeoning"
        ],
        "damageDice": "3d6+5",
        "damageAvg": 15
      }
    ],
    "environments": [
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Slashing",
      "Bludgeoning"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "grappler",
      "magic resistance"
    ],
    "subtype": "demon",
    "savingThrows": {
      "str": 9,
      "con": 9,
      "wis": 7,
      "cha": 7
    },
    "skills": {
      "Deception": 7,
      "Perception": 7
    },
    "spellcasting": {
      "ability": "int",
      "dc": 16,
      "atWill": [
        "Darkness",
        "Detect Magic",
        "Dispel Magic"
      ],
      "perDay": {
        "1": [
          "Confusion",
          "Fly",
          "Power Word Stun"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Demonic Restoration",
        "description": "If the glabrezu dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss."
      },
      {
        "name": "Magic Resistance",
        "description": "The glabrezu has Advantage on saving throws against spells and other magical effects."
      }
    ]
  },
  {
    "id": "treant",
    "name": "Treant",
    "source": "SRD52",
    "size": "Huge",
    "type": "Plant",
    "alignment": "Chaotic Good",
    "armor": {
      "ac": 16
    },
    "hitPoints": 138,
    "hitDice": "12d12 + 60",
    "speed": {
      "walk": 30
    },
    "abilities": {
      "str": 23,
      "dex": 8,
      "con": 21,
      "int": 12,
      "wis": 16,
      "cha": 12
    },
    "senses": [
      "passive Perception 13"
    ],
    "languages": [
      "Common",
      "Druidic",
      "Elvish",
      "Sylvan"
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [
      "Fire"
    ],
    "damageResistances": [
      "Bludgeoning",
      "Piercing"
    ],
    "damageImmunities": [],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The treant makes two Slam attacks."
      },
      {
        "name": "Slam",
        "description": "Melee Attack Roll: +10, reach 5 ft. Hit: 16 (3d6 + 6) Bludgeoning damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 5,
        "damageTypes": [
          "Bludgeoning"
        ],
        "damageDice": "3d6+6",
        "damageAvg": 16
      },
      {
        "name": "Hail of Bark",
        "description": "Ranged Attack Roll: +10, range 180 ft. Hit: 28 (4d10 + 6) Piercing damage.",
        "attackDelivery": "Ranged",
        "attackBonus": 10,
        "range": 180,
        "damageTypes": [
          "Piercing"
        ],
        "damageDice": "4d10+6",
        "damageAvg": 28
      },
      {
        "name": "Animate Trees (1/Day)",
        "description": "The treant magically animates up to two trees it can see within 60 feet of itself. Each tree uses the Treant stat block, except it has Intelligence and Charisma scores of 1, it can't speak, and it lacks this action. The tree takes its turn immediately after the treant on the same Initiative count, and it obeys the treant. A tree remains animate for 1 day or until it dies, the treant dies, or it is more than 120 feet from the treant. The tree then takes root if possible."
      }
    ],
    "environments": [
      "Forest"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Bludgeoning",
      "Piercing"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack"
    ],
    "specialAbilities": [
      {
        "name": "Siege Monster",
        "description": "The treant deals double damage to objects and structures."
      }
    ]
  },
  {
    "id": "young-blue-dragon",
    "name": "Young Blue Dragon",
    "source": "SRD52",
    "size": "Large",
    "type": "Dragon",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 152,
    "hitDice": "16d10 + 64",
    "speed": {
      "walk": 40,
      "fly": 80,
      "burrow": 20
    },
    "abilities": {
      "str": 21,
      "dex": 10,
      "con": 19,
      "int": 14,
      "wis": 13,
      "cha": 17
    },
    "senses": [
      "Blindsight 30 ft.",
      "Darkvision 120 ft.",
      "passive Perception 19"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Lightning"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +9, reach 10 ft. Hit: 12 (2d6 + 5) Slashing damage plus 5 (1d10) Lightning damage.",
        "attackDelivery": "Melee",
        "attackBonus": 9,
        "reach": 10,
        "damageTypes": [
          "Lightning",
          "Slashing"
        ],
        "damageDice": "2d6+5",
        "damageAvg": 12
      },
      {
        "name": "Lightning Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 16, each creature in a 60-foot-long, 5-foot-wide Line. Failure: 55 (10d10) Lightning damage. Success: Half damage.",
        "damageTypes": [
          "Lightning"
        ],
        "damageDice": "10d10",
        "damageAvg": 55
      }
    ],
    "environments": [
      "Coastal",
      "Desert"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly",
      "Burrow"
    ],
    "attackDamageTypes": [
      "Lightning",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "chromatic",
    "savingThrows": {
      "dex": 4,
      "wis": 5
    },
    "skills": {
      "Perception": 9,
      "Stealth": 4
    }
  },
  {
    "id": "young-silver-dragon",
    "name": "Young Silver Dragon",
    "source": "SRD52",
    "size": "Large",
    "type": "Dragon",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 18
    },
    "hitPoints": 168,
    "hitDice": "16d10 + 80",
    "speed": {
      "walk": 40,
      "fly": 80
    },
    "abilities": {
      "str": 23,
      "dex": 10,
      "con": 21,
      "int": 14,
      "wis": 11,
      "cha": 19
    },
    "senses": [
      "Blindsight 30 ft.",
      "Darkvision 120 ft.",
      "passive Perception 18"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 9,
    "proficiencyBonus": 4,
    "xp": 5000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Cold"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Paralyzing Breath."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +10, reach 10 ft. Hit: 15 (2d8 + 6) Slashing damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 10,
        "damageTypes": [
          "Slashing"
        ],
        "damageDice": "2d8+6",
        "damageAvg": 15
      },
      {
        "name": "Cold Breath (Recharge 5–6)",
        "description": "Constitution Saving Throw: DC 17, each creature in a 30-foot Cone. Failure: 49 (11d8) Cold damage. Success: Half damage.",
        "damageTypes": [
          "Cold"
        ],
        "damageDice": "11d8",
        "damageAvg": 49
      },
      {
        "name": "Paralyzing Breath",
        "description": "Constitution Saving Throw: DC 17, each creature in a 30-foot Cone. Failure: The target has the Incapacitated condition until the end of its next turn, when it repeats the save. Failure: The target has the Paralyzed condition, and it repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."
      }
    ],
    "environments": [
      "Mountain",
      "Urban"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Slashing",
      "Cold"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "metallic",
    "savingThrows": {
      "dex": 4,
      "wis": 4
    },
    "skills": {
      "History": 6,
      "Perception": 8,
      "Stealth": 4
    }
  },
  {
    "id": "aboleth",
    "name": "Aboleth",
    "source": "SRD52",
    "size": "Large",
    "type": "Aberration",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 17
    },
    "hitPoints": 150,
    "hitDice": "20d10 + 40",
    "speed": {
      "walk": 10,
      "swim": 40
    },
    "abilities": {
      "str": 21,
      "dex": 9,
      "con": 15,
      "int": 18,
      "wis": 15,
      "cha": 18
    },
    "senses": [
      "Darkvision 120 ft.",
      "passive Perception 20"
    ],
    "languages": [
      "Deep Speech; telepathy 120 ft."
    ],
    "challengeRating": 10,
    "proficiencyBonus": 4,
    "xp": 5900,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The aboleth makes two Tentacle attacks and uses either Consume Memories or Dominate Mind if available."
      },
      {
        "name": "Tentacle",
        "description": "Melee Attack Roll: +9, reach 15 ft. Hit: 12 (2d6 + 5) Bludgeoning damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 14) from one of four tentacles.",
        "attackDelivery": "Melee",
        "attackBonus": 9,
        "reach": 15,
        "damageTypes": [
          "Bludgeoning"
        ],
        "damageDice": "2d6+5",
        "damageAvg": 12
      },
      {
        "name": "Consume Memories",
        "description": "Intelligence Saving Throw: DC 16, one creature within 30 feet that is Charmed or Grappled by the aboleth. Failure: 10 (3d6) Psychic damage. Success: Half damage. Failure or Success: The aboleth gains the target's memories if the target is a Humanoid and is reduced to 0 Hit Points by this action.",
        "damageTypes": [
          "Psychic"
        ],
        "damageDice": "3d6",
        "damageAvg": 10
      },
      {
        "name": "Dominate Mind (2/Day)",
        "description": "Wisdom Saving Throw: DC 16, one creature the aboleth can see within 30 feet. Failure: The target has the Charmed condition until the aboleth dies or is on a different plane of existence from the target. While Charmed, the target acts as an ally to the aboleth and is under its control while within 60 feet of it. In addition, the aboleth and the target can communicate telepathically with each other over any distance.\nThe target repeats the save whenever it takes damage as well as after every 24 hours it spends at least 1 mile away from the aboleth, ending the effect on itself on a success."
      }
    ],
    "environments": [
      "Underdark",
      "Underwater"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Swim"
    ],
    "attackDamageTypes": [
      "Bludgeoning",
      "Psychic",
      "Acid"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "grappler",
      "charmer",
      "telepathy"
    ],
    "savingThrows": {
      "dex": 3,
      "con": 6,
      "int": 8,
      "wis": 6
    },
    "skills": {
      "History": 12,
      "Perception": 10
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The aboleth can breathe air and water."
      },
      {
        "name": "Eldritch Restoration",
        "description": "If destroyed, the aboleth gains a new body in 5d10 days, reviving with all its Hit Points in the Far Realm or another location chosen by the DM."
      },
      {
        "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
        "description": "If the aboleth fails a saving throw, it can choose to succeed instead."
      },
      {
        "name": "Mucus Cloud",
        "description": "While underwater, the aboleth is surrounded by mucus. Constitution Saving Throw: DC 14, each creature in a 5-foot Emanation originating from the aboleth at the end of the aboleth's turn. Failure: The target is cursed. Until the curse ends, the target's skin becomes slimy, the target can breathe air and water, and it can't regain Hit Points unless it is underwater.\nWhile the cursed creature is outside a body of water, the creature takes 6 (1d12) Acid damage at the end of every 10 minutes unless moisture is applied to its skin before those minutes have passed.",
        "damageTypes": [
          "Acid"
        ],
        "damageDice": "1d12",
        "damageAvg": 6
      },
      {
        "name": "Probing Telepathy",
        "description": "If a creature the aboleth can see communicates telepathically with the aboleth, the aboleth learns the creature's greatest desires."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Lash",
          "description": "The aboleth makes one Tentacle attack."
        },
        {
          "name": "Psychic Drain",
          "description": "If the aboleth has at least one creature Charmed or Grappled, it uses Consume Memories and regains 5 (1d10) Hit Points.",
          "damageDice": "1d10",
          "damageAvg": 5
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "deva",
    "name": "Deva",
    "source": "SRD52",
    "size": "Medium",
    "type": "Celestial",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 17
    },
    "hitPoints": 229,
    "hitDice": "27d8 + 108",
    "speed": {
      "walk": 30,
      "fly": 90,
      "hover": true
    },
    "abilities": {
      "str": 18,
      "dex": 18,
      "con": 18,
      "int": 17,
      "wis": 20,
      "cha": 20
    },
    "senses": [
      "Darkvision 120 ft.",
      "passive Perception 19"
    ],
    "languages": [
      "all; telepathy 120 ft."
    ],
    "challengeRating": 10,
    "proficiencyBonus": 4,
    "xp": 5900,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Radiant"
    ],
    "damageImmunities": [],
    "conditionImmunities": [
      "Charmed",
      "Exhaustion",
      "Frightened"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The deva makes two Holy Mace attacks."
      },
      {
        "name": "Holy Mace",
        "description": "Melee Attack Roll: +8, reach 5 ft. Hit: 7 (1d6 + 4) Bludgeoning damage plus 18 (4d8) Radiant damage.",
        "attackDelivery": "Melee",
        "attackBonus": 8,
        "reach": 5,
        "damageTypes": [
          "Bludgeoning",
          "Radiant"
        ],
        "damageDice": "1d6+4",
        "damageAvg": 7
      }
    ],
    "environments": [
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Hover"
    ],
    "attackDamageTypes": [
      "Bludgeoning",
      "Radiant"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "magic resistance",
      "flyer"
    ],
    "subtype": "angel",
    "savingThrows": {
      "wis": 9,
      "cha": 9
    },
    "skills": {
      "Insight": 9,
      "Perception": 9
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 17,
      "atWill": [
        "Detect Evil and Good",
        "Shapechange (Beast or Humanoid form only, no Temporary Hit Points gained from the spell, and no Concentration or Temporary Hit Points required to maintain the spell)"
      ],
      "perDay": {
        "1": [
          "Commune",
          "Raise Dead"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Exalted Restoration",
        "description": "If the deva dies outside Mount Celestia, its body disappears, and it gains a new body instantly, reviving with all its Hit Points somewhere in Mount Celestia."
      },
      {
        "name": "Magic Resistance",
        "description": "The deva has Advantage on saving throws against spells and other magical effects."
      }
    ]
  },
  {
    "id": "guardian-naga",
    "name": "Guardian Naga",
    "source": "SRD52",
    "size": "Large",
    "type": "Celestial",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 18
    },
    "hitPoints": 136,
    "hitDice": "16d10 + 48",
    "speed": {
      "walk": 40,
      "swim": 40,
      "climb": 40
    },
    "abilities": {
      "str": 19,
      "dex": 18,
      "con": 16,
      "int": 16,
      "wis": 19,
      "cha": 18
    },
    "senses": [
      "Darkvision 60 ft.",
      "passive Perception 14"
    ],
    "languages": [
      "Celestial",
      "Common"
    ],
    "challengeRating": 10,
    "proficiencyBonus": 4,
    "xp": 5900,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Poison"
    ],
    "conditionImmunities": [
      "Charmed",
      "Paralyzed",
      "Poisoned",
      "Restrained"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The naga makes two Bite attacks. It can replace any attack with a use of Poisonous Spittle.",
        "damageTypes": [
          "Poison"
        ]
      },
      {
        "name": "Bite",
        "description": "Melee Attack Roll: +8, reach 10 ft. Hit: 17 (2d12 + 4) Piercing damage plus 22 (4d10) Poison damage.",
        "attackDelivery": "Melee",
        "attackBonus": 8,
        "reach": 10,
        "damageTypes": [
          "Piercing",
          "Poison"
        ],
        "damageDice": "2d12+4",
        "damageAvg": 17
      },
      {
        "name": "Poisonous Spittle",
        "description": "Constitution Saving Throw: DC 16, one creature the naga can see within 60 feet. Failure: 31 (7d8) Poison damage, and the target has the Blinded condition until the start of the naga's next turn. Success: Half damage only.",
        "damageTypes": [
          "Poison"
        ],
        "damageDice": "7d8",
        "damageAvg": 31
      }
    ],
    "environments": [
      "Desert",
      "Forest",
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Swim",
      "Climb"
    ],
    "attackDamageTypes": [
      "Poison",
      "Piercing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack"
    ],
    "savingThrows": {
      "dex": 8,
      "con": 7,
      "int": 7,
      "wis": 8,
      "cha": 8
    },
    "skills": {
      "Arcana": 11,
      "History": 11,
      "Religion": 11
    },
    "spellcasting": {
      "ability": "wis",
      "dc": 16,
      "atWill": [
        "Thaumaturgy"
      ],
      "perDay": {
        "1": [
          "Clairvoyance",
          "Cure Wounds (level 6 version)",
          "Flame Strike (level 6 version)",
          "Geas",
          "True Seeing"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Celestial Restoration",
        "description": "If the naga dies, it returns to life in 1d6 days and regains all its Hit Points unless Dispel Evil and Good is cast on its remains."
      }
    ]
  },
  {
    "id": "stone-golem",
    "name": "Stone Golem",
    "source": "SRD52",
    "size": "Large",
    "type": "Construct",
    "alignment": "Unaligned",
    "armor": {
      "ac": 18
    },
    "hitPoints": 220,
    "hitDice": "21d10 + 105",
    "speed": {
      "walk": 30
    },
    "abilities": {
      "str": 22,
      "dex": 9,
      "con": 20,
      "int": 3,
      "wis": 11,
      "cha": 1
    },
    "senses": [
      "Darkvision 120 ft.",
      "passive Perception 10"
    ],
    "languages": [
      "understands Common plus two other languages but can't speak"
    ],
    "challengeRating": 10,
    "proficiencyBonus": 4,
    "xp": 5900,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Poison",
      "Psychic"
    ],
    "conditionImmunities": [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Petrified",
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The golem makes two attacks, using Slam or Force Bolt in any combination.",
        "damageTypes": [
          "Force"
        ]
      },
      {
        "name": "Slam",
        "description": "Melee Attack Roll: +10, reach 5 ft. Hit: 15 (2d8 + 6) Bludgeoning damage plus 9 (2d8) Force damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 5,
        "damageTypes": [
          "Bludgeoning",
          "Force"
        ],
        "damageDice": "2d8+6",
        "damageAvg": 15
      },
      {
        "name": "Force Bolt",
        "description": "Ranged Attack Roll: +9, range 120 ft. Hit: 22 (4d10) Force damage.",
        "attackDelivery": "Ranged",
        "attackBonus": 9,
        "range": 120,
        "damageTypes": [
          "Force"
        ],
        "damageDice": "4d10",
        "damageAvg": 22
      }
    ],
    "environments": [
      "Any"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Force",
      "Bludgeoning"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "magic resistance"
    ],
    "spellcasting": {
      "ability": "con",
      "dc": 17
    },
    "specialAbilities": [
      {
        "name": "Immutable Form",
        "description": "The golem can't shape-shift."
      },
      {
        "name": "Magic Resistance",
        "description": "The golem has Advantage on saving throws against spells and other magical effects."
      }
    ]
  },
  {
    "id": "young-gold-dragon",
    "name": "Young Gold Dragon",
    "source": "SRD52",
    "size": "Large",
    "type": "Dragon",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 18
    },
    "hitPoints": 178,
    "hitDice": "17d10 + 85",
    "speed": {
      "walk": 40,
      "fly": 80,
      "swim": 40
    },
    "abilities": {
      "str": 23,
      "dex": 14,
      "con": 21,
      "int": 16,
      "wis": 13,
      "cha": 20
    },
    "senses": [
      "Blindsight 30 ft.",
      "Darkvision 120 ft.",
      "passive Perception 19"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 10,
    "proficiencyBonus": 4,
    "xp": 5900,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Weakening Breath."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +10, reach 10 ft. Hit: 17 (2d10 + 6) Slashing damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 10,
        "damageTypes": [
          "Slashing"
        ],
        "damageDice": "2d10+6",
        "damageAvg": 17
      },
      {
        "name": "Fire Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 17, each creature in a 30-foot Cone. Failure: 55 (10d10) Fire damage. Success: Half damage.",
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "10d10",
        "damageAvg": 55
      },
      {
        "name": "Weakening Breath",
        "description": "Strength Saving Throw: DC 17, each creature that isn't currently affected by this breath in a 30-foot Cone. Failure: The target has Disadvantage on Strength-based D20 Tests and subtracts 3 (1d6) from its damage rolls. It repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically.",
        "damageDice": "1d6",
        "damageAvg": 3
      }
    ],
    "environments": [
      "Forest",
      "Grassland"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly",
      "Swim"
    ],
    "attackDamageTypes": [
      "Slashing",
      "Fire"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "metallic",
    "savingThrows": {
      "dex": 6,
      "wis": 5
    },
    "skills": {
      "Insight": 5,
      "Perception": 9,
      "Persuasion": 9,
      "Stealth": 6
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The dragon can breathe air and water."
      }
    ]
  },
  {
    "id": "young-red-dragon",
    "name": "Young Red Dragon",
    "source": "SRD52",
    "size": "Large",
    "type": "Dragon",
    "alignment": "Chaotic Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 178,
    "hitDice": "17d10 + 85",
    "speed": {
      "walk": 40,
      "fly": 80,
      "climb": 40
    },
    "abilities": {
      "str": 23,
      "dex": 10,
      "con": 21,
      "int": 14,
      "wis": 11,
      "cha": 19
    },
    "senses": [
      "Blindsight 30 ft.",
      "Darkvision 120 ft.",
      "passive Perception 18"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 10,
    "proficiencyBonus": 4,
    "xp": 5900,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +10, reach 10 ft. Hit: 13 (2d6 + 6) Slashing damage plus 3 (1d6) Fire damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 10,
        "damageTypes": [
          "Fire",
          "Slashing"
        ],
        "damageDice": "2d6+6",
        "damageAvg": 13
      },
      {
        "name": "Fire Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 17, each creature in a 30-foot Cone. Failure: 56 (16d6) Fire damage. Success: Half damage.",
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "16d6",
        "damageAvg": 56
      }
    ],
    "environments": [
      "Hill",
      "Mountain"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly",
      "Climb"
    ],
    "attackDamageTypes": [
      "Fire",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "chromatic",
    "savingThrows": {
      "dex": 4,
      "wis": 4
    },
    "skills": {
      "Perception": 8,
      "Stealth": 4
    }
  },
  {
    "id": "behir",
    "name": "Behir",
    "source": "SRD52",
    "size": "Huge",
    "type": "Monstrosity",
    "alignment": "Neutral Evil",
    "armor": {
      "ac": 17
    },
    "hitPoints": 168,
    "hitDice": "16d12 + 64",
    "speed": {
      "walk": 50,
      "climb": 50
    },
    "abilities": {
      "str": 23,
      "dex": 16,
      "con": 18,
      "int": 7,
      "wis": 14,
      "cha": 12
    },
    "senses": [
      "Darkvision 90 ft.",
      "passive Perception 16"
    ],
    "languages": [
      "Draconic"
    ],
    "challengeRating": 11,
    "proficiencyBonus": 4,
    "xp": 7200,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Lightning"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The behir makes one Bite attack and uses Constrict."
      },
      {
        "name": "Bite",
        "description": "Melee Attack Roll: +10, reach 10 ft. Hit: 19 (2d12 + 6) Piercing damage plus 11 (2d10) Lightning damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 10,
        "damageTypes": [
          "Lightning",
          "Piercing"
        ],
        "damageDice": "2d12+6",
        "damageAvg": 19
      },
      {
        "name": "Constrict",
        "description": "Strength Saving Throw: DC 18, one Large or smaller creature the behir can see within 5 feet. Failure: 28 (5d8 + 6) Bludgeoning damage. The target has the Grappled condition (escape DC 16), and it has the Restrained condition until the grapple ends.",
        "damageTypes": [
          "Bludgeoning"
        ],
        "damageDice": "5d8+6",
        "damageAvg": 28
      },
      {
        "name": "Lightning Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 16, each creature in a 90-foot-long, 5-foot-wide Line. Failure: 66 (12d10) Lightning damage. Success: Half damage.",
        "damageTypes": [
          "Lightning"
        ],
        "damageDice": "12d10",
        "damageAvg": 66
      }
    ],
    "environments": [
      "Underdark"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Climb"
    ],
    "attackDamageTypes": [
      "Lightning",
      "Piercing",
      "Bludgeoning",
      "Acid"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "swallow",
      "grappler",
      "breath weapon"
    ],
    "skills": {
      "Perception": 6,
      "Stealth": 7
    },
    "bonusActions": [
      {
        "name": "Swallow",
        "description": "Dexterity Saving Throw: DC 18, one Large or smaller creature Grappled by the behir (the behir can have only one creature swallowed at a time). Failure: The behir swallows the target, which is no longer Grappled. While swallowed, a creature has the Blinded and Restrained conditions, has Total Cover against attacks and other effects outside the behir, and takes 21 (6d6) Acid damage at the start of each of the behir's turns.\nIf the behir takes 30 damage or more on a single turn from the swallowed creature, the behir must succeed on a DC 14 Constitution saving throw at the end of that turn or regurgitate the creature, which falls in a space within 10 feet of the behir and has the Prone condition. If the behir dies, a swallowed creature is no longer Restrained and can escape from the corpse by using 15 feet of movement, exiting Prone.",
        "damageTypes": [
          "Acid"
        ],
        "damageDice": "6d6",
        "damageAvg": 21
      }
    ]
  },
  {
    "id": "djinni",
    "name": "Djinni",
    "source": "SRD52",
    "size": "Large",
    "type": "Elemental",
    "alignment": "Chaotic Good",
    "armor": {
      "ac": 17
    },
    "hitPoints": 218,
    "hitDice": "19d10 + 114",
    "speed": {
      "walk": 30,
      "fly": 90,
      "hover": true
    },
    "abilities": {
      "str": 21,
      "dex": 15,
      "con": 22,
      "int": 15,
      "wis": 16,
      "cha": 20
    },
    "senses": [
      "Darkvision 120 ft.",
      "passive Perception 13"
    ],
    "languages": [
      "Primordial (Auran)"
    ],
    "challengeRating": 11,
    "proficiencyBonus": 4,
    "xp": 7200,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Lightning",
      "Thunder"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The djinni makes three attacks, using Storm Blade or Storm Bolt in any combination."
      },
      {
        "name": "Storm Blade",
        "description": "Melee Attack Roll: +9, reach 5 feet. Hit: 12 (2d6 + 5) Slashing damage plus 7 (2d6) Lightning damage.",
        "attackDelivery": "Melee",
        "attackBonus": 9,
        "damageTypes": [
          "Lightning",
          "Slashing"
        ],
        "damageDice": "2d6+5",
        "damageAvg": 12
      },
      {
        "name": "Storm Bolt",
        "description": "Ranged Attack Roll: +9, range 120 feet. Hit: 13 (3d8) Thunder damage. If the target is a Large or smaller creature, it has the Prone condition.",
        "attackDelivery": "Ranged",
        "attackBonus": 9,
        "damageTypes": [
          "Thunder"
        ],
        "damageDice": "3d8",
        "damageAvg": 13
      },
      {
        "name": "Create Whirlwind",
        "description": "The djinni conjures a whirlwind at a point it can see within 120 feet. The whirlwind fills a 20-foot-radius, 60-foot-high Cylinder centered on that point. The whirlwind lasts until the djinni's Concentration on it ends. The djinni can move the whirlwind up to 20 feet at the start of each of its turns.\nWhenever the whirlwind enters a creature's space or a creature enters the whirlwind, that creature is subjected to the following effect. Strength Saving Throw: DC 17 (a creature makes this save only once per turn, and the djinni is unaffected). Failure: While in the whirlwind, the target has the Restrained condition and moves with the whirlwind. At the start of each of its turns, the Restrained target takes 21 (6d6) Thunder damage. At the end of each of its turns, the target repeats the save, ending the effect on itself on a success.",
        "damageTypes": [
          "Thunder"
        ],
        "damageDice": "6d6",
        "damageAvg": 21
      }
    ],
    "environments": [
      "Coastal",
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Hover"
    ],
    "attackDamageTypes": [
      "Lightning",
      "Slashing",
      "Thunder"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "magic resistance",
      "flyer"
    ],
    "subtype": "genie",
    "savingThrows": {
      "dex": 6,
      "wis": 7
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 17,
      "atWill": [
        "Detect Evil and Good",
        "Detect Magic"
      ],
      "perDay": {
        "1": [
          "Creation",
          "Gaseous Form",
          "Invisibility",
          "Major Image",
          "Plane Shift"
        ],
        "2": [
          "Create Food and Water (can create wine instead of water)",
          "Tongues",
          "Wind Walk"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Elemental Restoration",
        "description": "If the djinni dies outside the Elemental Plane of Air, its body dissolves into mist, and it gains a new body in 1d4 days, reviving with all its Hit Points somewhere on the Plane of Air."
      },
      {
        "name": "Magic Resistance",
        "description": "The djinni has Advantage on saving throws against spells and other magical effects."
      },
      {
        "name": "Wishes",
        "description": "The djinni has a 30 percent chance of knowing the Wish spell. If the djinni knows it, the djinni can cast it only on behalf of a non-genie creature who communicates a wish in a way the djinni can understand. If the djinni casts the spell for the creature, the djinni suffers none of the spell's stress. Once the djinni has cast it three times, the djinni can't do so again for 365 days."
      }
    ]
  },
  {
    "id": "efreeti",
    "name": "Efreeti",
    "source": "SRD52",
    "size": "Large",
    "type": "Elemental",
    "alignment": "True Neutral",
    "armor": {
      "ac": 17
    },
    "hitPoints": 212,
    "hitDice": "17d10 + 119",
    "speed": {
      "walk": 40,
      "fly": 60,
      "hover": true
    },
    "abilities": {
      "str": 22,
      "dex": 12,
      "con": 24,
      "int": 16,
      "wis": 15,
      "cha": 19
    },
    "senses": [
      "Darkvision 120 ft.",
      "passive Perception 12"
    ],
    "languages": [
      "Primordial (Ignan)"
    ],
    "challengeRating": 11,
    "proficiencyBonus": 4,
    "xp": 7200,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The efreeti makes three attacks, using Heated Blade or Hurl Flame in any combination."
      },
      {
        "name": "Heated Blade",
        "description": "Melee Attack Roll: +10, reach 5 ft. Hit: 13 (2d6 + 6) Slashing damage plus 13 (2d12) Fire damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 5,
        "damageTypes": [
          "Fire",
          "Slashing"
        ],
        "damageDice": "2d6+6",
        "damageAvg": 13
      },
      {
        "name": "Hurl Flame",
        "description": "Ranged Attack Roll: +8, range 120 ft. Hit: 24 (7d6) Fire damage.",
        "attackDelivery": "Ranged",
        "attackBonus": 8,
        "range": 120,
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "7d6",
        "damageAvg": 24
      }
    ],
    "environments": [
      "Desert",
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Hover"
    ],
    "attackDamageTypes": [
      "Fire",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "magic resistance",
      "flyer"
    ],
    "subtype": "genie",
    "savingThrows": {
      "wis": 6,
      "cha": 8
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 16,
      "atWill": [
        "Detect Magic",
        "Elementalism"
      ],
      "perDay": {
        "1": [
          "Gaseous Form",
          "Invisibility",
          "Major Image",
          "Plane Shift",
          "Tongues",
          "Wall of Fire (level 7 version)"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Elemental Restoration",
        "description": "If the efreeti dies outside the Elemental Plane of Fire, its body dissolves into ash, and it gains a new body in 1d4 days, reviving with all its Hit Points somewhere on the Plane of Fire.",
        "damageTypes": [
          "Fire"
        ]
      },
      {
        "name": "Magic Resistance",
        "description": "The efreeti has Advantage on saving throws against spells and other magical effects."
      },
      {
        "name": "Wishes",
        "description": "The efreeti has a 30 percent chance of knowing the Wish spell. If the efreeti knows it, the efreeti can cast it only on behalf of a non-genie creature who communicates a wish in a way the efreeti can understand. If the efreeti casts the spell for the creature, the efreeti suffers none of the spell's stress. Once the efreeti has cast it three times, the efreeti can't do so again for 365 days."
      }
    ]
  },
  {
    "id": "horned-devil",
    "name": "Horned Devil",
    "source": "SRD52",
    "size": "Large",
    "type": "Fiend",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 199,
    "hitDice": "19d10 + 95",
    "speed": {
      "walk": 30,
      "fly": 60
    },
    "abilities": {
      "str": 22,
      "dex": 17,
      "con": 21,
      "int": 12,
      "wis": 16,
      "cha": 18
    },
    "senses": [
      "Darkvision 150 ft. (unimpeded by magical Darkness)",
      "passive Perception 13"
    ],
    "languages": [
      "Infernal; telepathy 120 ft."
    ],
    "challengeRating": 11,
    "proficiencyBonus": 4,
    "xp": 7200,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire",
      "Poison"
    ],
    "conditionImmunities": [
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The devil makes three attacks, using Searing Fork or Hurl Flame in any combination. It can replace one attack with a use of Infernal Tail."
      },
      {
        "name": "Searing Fork",
        "description": "Melee Attack Roll: +10, reach 10 ft. Hit: 15 (2d8 + 6) Piercing damage plus 9 (2d8) Fire damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 10,
        "damageTypes": [
          "Fire",
          "Piercing"
        ],
        "damageDice": "2d8+6",
        "damageAvg": 15
      },
      {
        "name": "Hurl Flame",
        "description": "Ranged Attack Roll: +8, range 150 ft. Hit: 26 (5d8 + 4) Fire damage. If the target is a flammable object that isn't being worn or carried, it starts burning.",
        "attackDelivery": "Ranged",
        "attackBonus": 8,
        "range": 150,
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "5d8+4",
        "damageAvg": 26
      },
      {
        "name": "Infernal Tail",
        "description": "Dexterity Saving Throw: DC 17, one creature the devil can see within 10 feet. Failure: 10 (1d8 + 6) Necrotic damage, and the target receives an infernal wound if it doesn't have one. While wounded, the target loses 10 (3d6) Hit Points at the start of each of its turns. The wound closes after 1 minute, after a spell restores Hit Points to the target, or after the target or a creature within 5 feet of it takes an action to stanch the wound, doing so by succeeding on a DC 17 Wisdom (Medicine) check.",
        "damageTypes": [
          "Necrotic"
        ],
        "damageDice": "1d8+6",
        "damageAvg": 10
      }
    ],
    "environments": [
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Fire",
      "Piercing",
      "Necrotic"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "magic resistance",
      "flyer"
    ],
    "subtype": "devil",
    "savingThrows": {
      "str": 10,
      "dex": 7,
      "wis": 7,
      "cha": 8
    },
    "specialAbilities": [
      {
        "name": "Diabolical Restoration",
        "description": "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells."
      },
      {
        "name": "Magic Resistance",
        "description": "The devil has Advantage on saving throws against spells and other magical effects."
      }
    ]
  },
  {
    "id": "remorhaz",
    "name": "Remorhaz",
    "source": "SRD52",
    "size": "Huge",
    "type": "Monstrosity",
    "alignment": "Unaligned",
    "armor": {
      "ac": 17
    },
    "hitPoints": 195,
    "hitDice": "17d12 + 85",
    "speed": {
      "walk": 40,
      "burrow": 30
    },
    "abilities": {
      "str": 24,
      "dex": 13,
      "con": 21,
      "int": 4,
      "wis": 10,
      "cha": 5
    },
    "senses": [
      "Darkvision 60 ft.",
      "Tremorsense 60 ft.",
      "passive Perception 10"
    ],
    "languages": [],
    "challengeRating": 11,
    "proficiencyBonus": 4,
    "xp": 7200,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Cold",
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Bite",
        "description": "Melee Attack Roll: +11, reach 10 ft. Hit: 18 (2d10 + 7) Piercing damage plus 14 (4d6) Fire damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 17), and it has the Restrained condition until the grapple ends.",
        "attackDelivery": "Melee",
        "attackBonus": 11,
        "reach": 10,
        "damageTypes": [
          "Fire",
          "Piercing"
        ],
        "damageDice": "2d10+7",
        "damageAvg": 18
      }
    ],
    "environments": [
      "Arctic"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Burrow"
    ],
    "attackDamageTypes": [
      "Fire",
      "Piercing",
      "Acid"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "swallow",
      "grappler"
    ],
    "specialAbilities": [
      {
        "name": "Heat Aura",
        "description": "At the end of each of the remorhaz's turns, each creature in a 5-foot Emanation originating from the remorhaz takes 16 (3d10) Fire damage.",
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "3d10",
        "damageAvg": 16
      }
    ],
    "bonusActions": [
      {
        "name": "Swallow",
        "description": "Strength Saving Throw: DC 19, one Large or smaller creature Grappled by the remorhaz (it can have up to two creatures swallowed at a time). Failure: The target is swallowed by the remorhaz, and the Grappled condition ends. A swallowed creature has the Blinded and Restrained conditions, it has Total Cover against attacks and other effects outside the remorhaz, and it takes 10 (3d6) Acid damage plus 10 (3d6) Fire damage at the start of each of the remorhaz's turns.\nIf the remorhaz takes 30 damage or more on a single turn from a creature inside it, the remorhaz must succeed on a DC 15 Constitution saving throw at the end of that turn or regurgitate all swallowed creatures, each of which falls in a space within 5 feet of the remorhaz and has the Prone condition. If the remorhaz dies, any swallowed creature no longer has the Restrained condition and can escape from the corpse by using 15 feet of movement, exiting Prone.",
        "damageTypes": [
          "Acid",
          "Fire"
        ],
        "damageDice": "3d6",
        "damageAvg": 10
      }
    ]
  },
  {
    "id": "roc",
    "name": "Roc",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Monstrosity",
    "alignment": "Unaligned",
    "armor": {
      "ac": 15
    },
    "hitPoints": 248,
    "hitDice": "16d20 + 80",
    "speed": {
      "walk": 20,
      "fly": 120
    },
    "abilities": {
      "str": 28,
      "dex": 10,
      "con": 20,
      "int": 3,
      "wis": 10,
      "cha": 9
    },
    "senses": [
      "passive Perception 18"
    ],
    "languages": [],
    "challengeRating": 11,
    "proficiencyBonus": 4,
    "xp": 7200,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The roc makes two Beak attacks. It can replace one attack with a Talons attack."
      },
      {
        "name": "Beak",
        "description": "Melee Attack Roll: +13, reach 10 ft. Hit: 28 (3d12 + 9) Piercing damage.",
        "attackDelivery": "Melee",
        "attackBonus": 13,
        "reach": 10,
        "damageTypes": [
          "Piercing"
        ],
        "damageDice": "3d12+9",
        "damageAvg": 28
      },
      {
        "name": "Talons",
        "description": "Melee Attack Roll: +13, reach 5 ft. Hit: 23 (4d6 + 9) Slashing damage. If the target is a Huge or smaller creature, it has the Grappled condition (escape DC 19) from both talons, and it has the Restrained condition until the grapple ends.",
        "attackDelivery": "Melee",
        "attackBonus": 13,
        "reach": 5,
        "damageTypes": [
          "Slashing"
        ],
        "damageDice": "4d6+9",
        "damageAvg": 23
      }
    ],
    "environments": [
      "Arctic",
      "Coastal",
      "Desert",
      "Hill",
      "Mountain"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Piercing",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "grappler",
      "flyer"
    ],
    "savingThrows": {
      "dex": 4,
      "wis": 4
    },
    "skills": {
      "Perception": 8
    },
    "bonusActions": [
      {
        "name": "Swoop (Recharge 5–6)",
        "description": "If the roc has a creature Grappled, the roc flies up to half its Fly Speed without provoking Opportunity Attacks and drops that creature."
      }
    ]
  },
  {
    "id": "sphinx-of-lore",
    "name": "Sphinx of Lore",
    "source": "SRD52",
    "size": "Large",
    "type": "Celestial",
    "alignment": "Lawful Neutral",
    "armor": {
      "ac": 17
    },
    "hitPoints": 170,
    "hitDice": "20d10 + 60",
    "speed": {
      "walk": 40,
      "fly": 60
    },
    "abilities": {
      "str": 18,
      "dex": 15,
      "con": 16,
      "int": 18,
      "wis": 18,
      "cha": 18
    },
    "senses": [
      "Truesight 120 ft.",
      "passive Perception 18"
    ],
    "languages": [
      "Celestial",
      "Common"
    ],
    "challengeRating": 11,
    "proficiencyBonus": 4,
    "xp": 7200,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Necrotic",
      "Radiant"
    ],
    "damageImmunities": [
      "Psychic"
    ],
    "conditionImmunities": [
      "Charmed",
      "Frightened"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The sphinx makes three Claw attacks."
      },
      {
        "name": "Claw",
        "description": "Melee Attack Roll: +8, reach 5 ft. Hit: 14 (3d6 + 4) Slashing damage.",
        "attackDelivery": "Melee",
        "attackBonus": 8,
        "reach": 5,
        "damageTypes": [
          "Slashing"
        ],
        "damageDice": "3d6+4",
        "damageAvg": 14
      },
      {
        "name": "Mind-Rending Roar (Recharge 5–6)",
        "description": "Wisdom Saving Throw: DC 16, each enemy in a 300-foot Emanation originating from the sphinx. Failure: 35 (10d6) Psychic damage, and the target has the Incapacitated condition until the start of the sphinx's next turn.",
        "damageTypes": [
          "Psychic"
        ],
        "damageDice": "10d6",
        "damageAvg": 35
      }
    ],
    "environments": [
      "Desert",
      "Planar"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Slashing",
      "Psychic"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "flyer"
    ],
    "skills": {
      "Arcana": 12,
      "History": 12,
      "Perception": 8,
      "Religion": 12
    },
    "spellcasting": {
      "ability": "int",
      "dc": 16,
      "atWill": [
        "Detect Magic",
        "Identify",
        "Mage Hand",
        "Minor Illusion",
        "Prestidigitation"
      ],
      "perDay": {
        "1": [
          "Dispel Magic",
          "Legend Lore",
          "Locate Object",
          "Plane Shift",
          "Remove Curse",
          "Tongues"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Inscrutable",
        "description": "No magic can observe the sphinx remotely or detect its thoughts without its permission. Wisdom (Insight) checks made to ascertain its intentions or sincerity are made with Disadvantage."
      },
      {
        "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
        "description": "If the sphinx fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Arcane Prowl",
          "description": "The sphinx can teleport up to 30 feet to an unoccupied space it can see, and it makes one Claw attack."
        },
        {
          "name": "Weight of Years",
          "description": "Constitution Saving Throw: DC 16, one creature the sphinx can see within 120 feet. Failure: The target gains 1 Exhaustion level. While the target has any Exhaustion levels, it appears 3d10 years older. Failure or Success: The sphinx can't take this action again until the start of its next turn."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "archmage",
    "name": "Archmage",
    "source": "SRD52",
    "size": "Small",
    "type": "Humanoid",
    "alignment": "True Neutral",
    "armor": {
      "ac": 17
    },
    "hitPoints": 170,
    "hitDice": "31d8 + 31",
    "speed": {
      "walk": 30
    },
    "abilities": {
      "str": 10,
      "dex": 14,
      "con": 12,
      "int": 20,
      "wis": 15,
      "cha": 16
    },
    "senses": [
      "passive Perception 16"
    ],
    "languages": [
      "Common plus five other languages"
    ],
    "challengeRating": 12,
    "proficiencyBonus": 4,
    "xp": 8400,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Psychic"
    ],
    "conditionImmunities": [
      "Charmed"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The archmage makes four Arcane Burst attacks."
      },
      {
        "name": "Arcane Burst",
        "description": "Melee or Ranged Attack Roll: +9, reach 5 ft. or range 150 ft. Hit: 27 (4d10 + 5) Force damage.",
        "attackDelivery": "Melee",
        "attackBonus": 9,
        "reach": 5,
        "range": 150,
        "damageTypes": [
          "Force"
        ],
        "damageDice": "4d10+5",
        "damageAvg": 27
      }
    ],
    "environments": [
      "Any"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Force"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "magic resistance"
    ],
    "subtype": "wizard",
    "savingThrows": {
      "int": 9,
      "wis": 6
    },
    "skills": {
      "Arcana": 13,
      "History": 9,
      "Perception": 6
    },
    "spellcasting": {
      "ability": "int",
      "dc": 17,
      "atWill": [
        "Detect Magic",
        "Detect Thoughts",
        "Disguise Self",
        "Invisibility",
        "Light",
        "Mage Armor (included in AC)",
        "Mage Hand",
        "Prestidigitation"
      ],
      "perDay": {
        "1": [
          "Cone of Cold (level 9 version)",
          "Mind Blank (cast before combat)",
          "Scrying",
          "Teleport"
        ],
        "2": [
          "Fly",
          "Lightning Bolt (level 7 version)"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Magic Resistance",
        "description": "The archmage has Advantage on saving throws against spells and other magical effects."
      }
    ]
  },
  {
    "id": "erinyes",
    "name": "Erinyes",
    "source": "SRD52",
    "size": "Medium",
    "type": "Fiend",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 178,
    "hitDice": "21d8 + 84",
    "speed": {
      "walk": 30,
      "fly": 60
    },
    "abilities": {
      "str": 18,
      "dex": 16,
      "con": 18,
      "int": 14,
      "wis": 14,
      "cha": 18
    },
    "senses": [
      "Truesight 120 ft.",
      "passive Perception 16"
    ],
    "languages": [
      "Infernal; telepathy 120 ft."
    ],
    "challengeRating": 12,
    "proficiencyBonus": 4,
    "xp": 8400,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Cold"
    ],
    "damageImmunities": [
      "Fire",
      "Poison"
    ],
    "conditionImmunities": [
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The erinyes makes three Withering Sword attacks and can use Entangling Rope."
      },
      {
        "name": "Withering Sword",
        "description": "Melee Attack Roll: +8, reach 5 ft. Hit: 13 (2d8 + 4) Slashing damage plus 11 (2d10) Necrotic damage.",
        "attackDelivery": "Melee",
        "attackBonus": 8,
        "reach": 5,
        "damageTypes": [
          "Necrotic",
          "Slashing"
        ],
        "damageDice": "2d8+4",
        "damageAvg": 13
      },
      {
        "name": "Entangling Rope (Requires Magic Rope)",
        "description": "Strength Saving Throw: DC 16, one creature the erinyes can see within 120 feet. Failure: 14 (4d6) Force damage, and the target has the Restrained condition until the rope is destroyed, the erinyes uses a Bonus Action to release the target, or the erinyes uses Entangling Rope again.",
        "damageTypes": [
          "Force"
        ],
        "damageDice": "4d6",
        "damageAvg": 14
      }
    ],
    "environments": [
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Necrotic",
      "Slashing",
      "Force",
      "Poison",
      "Psychic"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "magic resistance",
      "flyer"
    ],
    "subtype": "devil",
    "savingThrows": {
      "dex": 7,
      "con": 8,
      "cha": 8
    },
    "skills": {
      "Perception": 6,
      "Persuasion": 8
    },
    "specialAbilities": [
      {
        "name": "Diabolical Restoration",
        "description": "If the erinyes dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells."
      },
      {
        "name": "Magic Resistance",
        "description": "The erinyes has Advantage on saving throws against spells and other magical effects."
      },
      {
        "name": "Magic Rope",
        "description": "The erinyes has a magic rope. While bearing it, the erinyes can use the Entangling Rope action. The rope has AC 20, HP 90, and Immunity to Poison and Psychic damage. The rope turns to dust if reduced to 0 Hit Points, if it is 5+ feet away from the erinyes for 1 hour or more, or if the erinyes dies. If the rope is damaged or destroyed, the erinyes can fully restore it when finishing a Short or Long Rest.",
        "damageTypes": [
          "Poison",
          "Psychic"
        ]
      }
    ],
    "reactions": [
      {
        "name": "Parry",
        "description": "Trigger: The erinyes is hit by a melee attack roll while holding a weapon. Response: The erinyes adds 4 to its AC against that attack, possibly causing it to miss.",
        "attackDelivery": "Melee"
      }
    ]
  },
  {
    "id": "adult-brass-dragon",
    "name": "Adult Brass Dragon",
    "source": "SRD52",
    "size": "Huge",
    "type": "Dragon",
    "alignment": "Chaotic Good",
    "armor": {
      "ac": 18
    },
    "hitPoints": 172,
    "hitDice": "15d12 + 75",
    "speed": {
      "walk": 40,
      "fly": 80,
      "burrow": 30
    },
    "abilities": {
      "str": 23,
      "dex": 10,
      "con": 21,
      "int": 14,
      "wis": 13,
      "cha": 17
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 21"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 13,
    "proficiencyBonus": 5,
    "xp": 10000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of (A) Sleep Breath or (B) Spellcasting to cast Scorching Ray."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +11, reach 10 ft. Hit: 17 (2d10 + 6) Slashing damage plus 4 (1d8) Fire damage.",
        "attackDelivery": "Melee",
        "attackBonus": 11,
        "reach": 10,
        "damageTypes": [
          "Fire",
          "Slashing"
        ],
        "damageDice": "2d10+6",
        "damageAvg": 17
      },
      {
        "name": "Fire Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 18, each creature in a 60-foot-long, 5-foot-wide Line. Failure: 45 (10d8) Fire damage. Success: Half damage.",
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "10d8",
        "damageAvg": 45
      },
      {
        "name": "Sleep Breath",
        "description": "Constitution Saving Throw: DC 18, each creature in a 60-foot Cone. Failure: The target has the Incapacitated condition until the end of its next turn, at which point it repeats the save. Failure: The target has the Unconscious condition for 10 minutes. This effect ends for the target if it takes damage or a creature within 5 feet of it takes an action to wake it."
      }
    ],
    "environments": [
      "Desert"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Burrow"
    ],
    "attackDamageTypes": [
      "Fire",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "metallic",
    "savingThrows": {
      "dex": 5,
      "wis": 6
    },
    "skills": {
      "History": 7,
      "Perception": 11,
      "Persuasion": 8,
      "Stealth": 5
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 16,
      "atWill": [
        "Detect Magic",
        "Minor Illusion",
        "Scorching Ray",
        "Shapechange (Beast or Humanoid form only, no Temporary Hit Points gained from the spell, and no Concentration or Temporary Hit Points required to maintain the spell)",
        "Speak with Animals"
      ],
      "perDay": {
        "1": [
          "Detect Thoughts",
          "Control Weather"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Blazing Light",
          "description": "The dragon uses Spellcasting to cast Scorching Ray."
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        },
        {
          "name": "Scorching Sands",
          "description": "Dexterity Saving Throw: DC 16, one creature the dragon can see within 120 feet. Failure: 27 (6d8) Fire damage, and the target's Speed is halved until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Fire"
          ],
          "damageDice": "6d8",
          "damageAvg": 27
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "adult-white-dragon",
    "name": "Adult White Dragon",
    "source": "SRD52",
    "size": "Huge",
    "type": "Dragon",
    "alignment": "Chaotic Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 200,
    "hitDice": "16d12 + 96",
    "speed": {
      "walk": 40,
      "fly": 80,
      "swim": 40,
      "burrow": 30
    },
    "abilities": {
      "str": 22,
      "dex": 10,
      "con": 22,
      "int": 8,
      "wis": 12,
      "cha": 12
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 21"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 13,
    "proficiencyBonus": 5,
    "xp": 10000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Cold"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +11, reach 10 ft. Hit: 13 (2d6 + 6) Slashing damage plus 4 (1d8) Cold damage.",
        "attackDelivery": "Melee",
        "attackBonus": 11,
        "reach": 10,
        "damageTypes": [
          "Cold",
          "Slashing"
        ],
        "damageDice": "2d6+6",
        "damageAvg": 13
      },
      {
        "name": "Cold Breath (Recharge 5–6)",
        "description": "Constitution Saving Throw: DC 19, each creature in a 60-foot Cone. Failure: 54 (12d8) Cold damage. Success: Half damage.",
        "damageTypes": [
          "Cold"
        ],
        "damageDice": "12d8",
        "damageAvg": 54
      }
    ],
    "environments": [
      "Arctic"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Swim",
      "Burrow"
    ],
    "attackDamageTypes": [
      "Cold",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "chromatic",
    "savingThrows": {
      "dex": 5,
      "wis": 6
    },
    "skills": {
      "Perception": 11,
      "Stealth": 5
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 14
    },
    "specialAbilities": [
      {
        "name": "Ice Walk",
        "description": "The dragon can move across and climb icy surfaces without needing to make an ability check. Additionally, Difficult Terrain composed of ice or snow doesn't cost it extra movement."
      },
      {
        "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Freezing Burst",
          "description": "Constitution Saving Throw: DC 14, each creature in a 30-foot-radius Sphere centered on a point the dragon can see within 120 feet. Failure: 7 (2d6) Cold damage, and the target's Speed is 0 until the end of the target's next turn. Failure or Success: The dragon can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Cold"
          ],
          "damageDice": "2d6",
          "damageAvg": 7
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "nalfeshnee",
    "name": "Nalfeshnee",
    "source": "SRD52",
    "size": "Large",
    "type": "Fiend",
    "alignment": "Chaotic Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 184,
    "hitDice": "16d10 + 96",
    "speed": {
      "walk": 20,
      "fly": 30
    },
    "abilities": {
      "str": 21,
      "dex": 10,
      "con": 22,
      "int": 19,
      "wis": 12,
      "cha": 15
    },
    "senses": [
      "Truesight 120 ft.",
      "passive Perception 11"
    ],
    "languages": [
      "Abyssal; telepathy 120 ft."
    ],
    "challengeRating": 13,
    "proficiencyBonus": 5,
    "xp": 10000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Cold",
      "Fire",
      "Lightning"
    ],
    "damageImmunities": [
      "Poison"
    ],
    "conditionImmunities": [
      "Frightened",
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The nalfeshnee makes three Rend attacks."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +10, reach 10 ft. Hit: 16 (2d10 + 5) Slashing damage plus 11 (2d10) Force damage.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 10,
        "damageTypes": [
          "Force",
          "Slashing"
        ],
        "damageDice": "2d10+5",
        "damageAvg": 16
      },
      {
        "name": "Teleport",
        "description": "The nalfeshnee teleports up to 120 feet to an unoccupied space it can see."
      }
    ],
    "environments": [
      "Planar"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Force",
      "Slashing",
      "Psychic"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "frightening",
      "magic resistance",
      "flyer"
    ],
    "subtype": "demon",
    "savingThrows": {
      "con": 11,
      "int": 9,
      "wis": 6,
      "cha": 7
    },
    "specialAbilities": [
      {
        "name": "Demonic Restoration",
        "description": "If the nalfeshnee dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss."
      },
      {
        "name": "Magic Resistance",
        "description": "The nalfeshnee has Advantage on saving throws against spells and other magical effects."
      }
    ],
    "bonusActions": [
      {
        "name": "Horror Nimbus (Recharge 5–6)",
        "description": "Wisdom Saving Throw: DC 15, each creature in a 15-foot Emanation originating from the nalfeshnee. Failure: 28 (8d6) Psychic damage, and the target has the Frightened condition for 1 minute, until it takes damage, or until it ends its turn with the nalfeshnee out of line of sight. Success: The target is immune to this nalfeshnee's Horror Nimbus for 24 hours.",
        "damageTypes": [
          "Psychic"
        ],
        "damageDice": "8d6",
        "damageAvg": 28
      }
    ],
    "reactions": [
      {
        "name": "Pursuit",
        "description": "Trigger: Another creature the nalfeshnee can see ends its move within 120 feet of the nalfeshnee. Response: The nalfeshnee uses Teleport, but its destination space must be within 10 feet of the triggering creature."
      }
    ]
  },
  {
    "id": "rakshasa",
    "name": "Rakshasa",
    "source": "SRD52",
    "size": "Medium",
    "type": "Fiend",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 17
    },
    "hitPoints": 221,
    "hitDice": "26d8 + 104",
    "speed": {
      "walk": 40
    },
    "abilities": {
      "str": 14,
      "dex": 17,
      "con": 18,
      "int": 13,
      "wis": 16,
      "cha": 20
    },
    "senses": [
      "Truesight 60 ft.",
      "passive Perception 18"
    ],
    "languages": [
      "Common",
      "Infernal"
    ],
    "challengeRating": 13,
    "proficiencyBonus": 5,
    "xp": 10000,
    "damageVulnerabilities": [
      "Piercing"
    ],
    "damageResistances": [],
    "damageImmunities": [],
    "conditionImmunities": [
      "Charmed",
      "Frightened"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The rakshasa makes three Cursed Touch attacks."
      },
      {
        "name": "Cursed Touch",
        "description": "Melee Attack Roll: +10, reach 5 ft. Hit: 12 (2d6 + 5) Slashing damage plus 19 (3d12) Necrotic damage. If the target is a creature, it is cursed. While cursed, the target gains no benefit from finishing a Short or Long Rest.",
        "attackDelivery": "Melee",
        "attackBonus": 10,
        "reach": 5,
        "damageTypes": [
          "Necrotic",
          "Slashing"
        ],
        "damageDice": "2d6+5",
        "damageAvg": 12
      },
      {
        "name": "Baleful Command (Recharge 5–6)",
        "description": "Wisdom Saving Throw: DC 18, each enemy in a 30-foot Emanation originating from the rakshasa. Failure: 28 (8d6) Psychic damage, and the target has the Frightened and Incapacitated conditions until the start of the rakshasa's next turn.",
        "damageTypes": [
          "Psychic"
        ],
        "damageDice": "8d6",
        "damageAvg": 28
      }
    ],
    "environments": [
      "Planar",
      "Urban"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Necrotic",
      "Slashing",
      "Psychic"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "frightening",
      "magic resistance"
    ],
    "skills": {
      "Deception": 10,
      "Insight": 8,
      "Perception": 8
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 18,
      "atWill": [
        "Detect Magic",
        "Detect Thoughts",
        "Disguise Self",
        "Mage Hand",
        "Minor Illusion"
      ],
      "perDay": {
        "1": [
          "Fly",
          "Invisibility",
          "Major Image",
          "Plane Shift"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Greater Magic Resistance",
        "description": "The rakshasa automatically succeeds on saving throws against spells and other magical effects, and the attack rolls of spells automatically miss it. Without the rakshasa's permission, no spell can observe the rakshasa remotely or detect its thoughts, creature type, or alignment."
      },
      {
        "name": "Fiendish Restoration",
        "description": "If the rakshasa dies outside the Nine Hells, its body turns to ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells."
      }
    ]
  },
  {
    "id": "storm-giant",
    "name": "Storm Giant",
    "source": "SRD52",
    "size": "Huge",
    "type": "Giant",
    "alignment": "Chaotic Good",
    "armor": {
      "ac": 16
    },
    "hitPoints": 230,
    "hitDice": "20d12 + 100",
    "speed": {
      "walk": 50,
      "fly": 25,
      "swim": 50,
      "hover": true
    },
    "abilities": {
      "str": 29,
      "dex": 14,
      "con": 20,
      "int": 16,
      "wis": 20,
      "cha": 18
    },
    "senses": [
      "Darkvision 120 ft.",
      "Truesight 30 ft.",
      "passive Perception 20"
    ],
    "languages": [
      "Common",
      "Giant"
    ],
    "challengeRating": 13,
    "proficiencyBonus": 5,
    "xp": 10000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Cold"
    ],
    "damageImmunities": [
      "Lightning",
      "Thunder"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The giant makes two attacks, using Storm Sword or Thunderbolt in any combination.",
        "damageTypes": [
          "Thunder"
        ]
      },
      {
        "name": "Storm Sword",
        "description": "Melee Attack Roll: +14, reach 10 ft. Hit: 23 (4d6 + 9) Slashing damage plus 13 (3d8) Lightning damage.",
        "attackDelivery": "Melee",
        "attackBonus": 14,
        "reach": 10,
        "damageTypes": [
          "Lightning",
          "Slashing"
        ],
        "damageDice": "4d6+9",
        "damageAvg": 23
      },
      {
        "name": "Thunderbolt",
        "description": "Ranged Attack Roll: +14, range 500 ft. Hit: 22 (2d12 + 9) Lightning damage, and the target has the Blinded and Deafened conditions until the start of the giant's next turn.",
        "attackDelivery": "Ranged",
        "attackBonus": 14,
        "range": 500,
        "damageTypes": [
          "Lightning"
        ],
        "damageDice": "2d12+9",
        "damageAvg": 22
      },
      {
        "name": "Lightning Storm (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 18, each creature in a 10-foot-radius, 40-foot-high Cylinder originating from a point the giant can see within 500 feet. Failure: 55 (10d10) Lightning damage. Success: Half damage.",
        "damageTypes": [
          "Lightning"
        ],
        "damageDice": "10d10",
        "damageAvg": 55
      }
    ],
    "environments": [
      "Coastal",
      "Underwater"
    ],
    "isLegendary": false,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Swim",
      "Hover"
    ],
    "attackDamageTypes": [
      "Thunder",
      "Lightning",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "flyer"
    ],
    "savingThrows": {
      "str": 14,
      "con": 10,
      "wis": 10,
      "cha": 9
    },
    "skills": {
      "Arcana": 8,
      "Athletics": 14,
      "History": 8,
      "Perception": 10
    },
    "spellcasting": {
      "ability": "wis",
      "dc": 18,
      "atWill": [
        "Detect Magic",
        "Light"
      ],
      "perDay": {
        "1": [
          "Control Weather"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The giant can breathe air and water."
      }
    ]
  },
  {
    "id": "vampire",
    "name": "Vampire",
    "source": "SRD52",
    "size": "Small",
    "type": "Undead",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 16
    },
    "hitPoints": 195,
    "hitDice": "23d8 + 92",
    "speed": {
      "walk": 40,
      "climb": 40
    },
    "abilities": {
      "str": 18,
      "dex": 18,
      "con": 18,
      "int": 17,
      "wis": 15,
      "cha": 18
    },
    "senses": [
      "Darkvision 120 ft.",
      "passive Perception 17"
    ],
    "languages": [
      "Common plus two other languages"
    ],
    "challengeRating": 13,
    "proficiencyBonus": 5,
    "xp": 10000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Necrotic"
    ],
    "damageImmunities": [],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack (Vampire Form Only)",
        "description": "The vampire makes two Grave Strike attacks and uses Bite."
      },
      {
        "name": "Grave Strike (Vampire Form Only)",
        "description": "Melee Attack Roll: +9, reach 5 ft. Hit: 8 (1d8 + 4) Bludgeoning damage plus 7 (2d6) Necrotic damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 14) from one of two hands.",
        "attackDelivery": "Melee",
        "attackBonus": 9,
        "reach": 5,
        "damageTypes": [
          "Bludgeoning",
          "Necrotic"
        ],
        "damageDice": "1d8+4",
        "damageAvg": 8
      },
      {
        "name": "Bite (Bat or Vampire Form Only)",
        "description": "Constitution Saving Throw: DC 17, one creature within 5 feet that is willing or that has the Grappled, Incapacitated, or Restrained condition. Failure: 6 (1d4 + 4) Piercing damage plus 13 (3d8) Necrotic damage. The target's Hit Point maximum decreases by an amount equal to the Necrotic damage taken, and the vampire regains Hit Points equal to that amount. A Humanoid reduced to 0 Hit Points by this damage and then buried rises the following sunset as a Vampire Spawn under the vampire's control.",
        "damageTypes": [
          "Necrotic",
          "Piercing"
        ],
        "damageDice": "1d4+4",
        "damageAvg": 6
      }
    ],
    "environments": [
      "Underdark",
      "Urban"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Climb"
    ],
    "attackDamageTypes": [
      "Bludgeoning",
      "Necrotic",
      "Piercing",
      "Acid",
      "Radiant"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "grappler"
    ],
    "savingThrows": {
      "dex": 9,
      "con": 9,
      "wis": 7,
      "cha": 9
    },
    "skills": {
      "Perception": 7,
      "Stealth": 9
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 17
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
        "description": "If the vampire fails a saving throw, it can choose to succeed instead."
      },
      {
        "name": "Misty Escape",
        "description": "If the vampire drops to 0 Hit Points outside its resting place, the vampire uses Shape-Shift to become mist (no action required). If it can't use Shape-Shift, it is destroyed.\nWhile it has 0 Hit Points in mist form, it can't return to its vampire form, and it must reach its resting place within 2 hours or be destroyed. Once in its resting place, it returns to its vampire form and has the Paralyzed condition until it regains any Hit Points, and it regains 1 Hit Point after spending 1 hour there."
      },
      {
        "name": "Spider Climb",
        "description": "The vampire can climb difficult surfaces, including along ceilings, without needing to make an ability check."
      },
      {
        "name": "Vampire Weakness",
        "description": "The vampire has these weaknesses:\nForbiddance: The vampire can't enter a residence without an invitation from an occupant.\nRunning Water: The vampire takes 20 Acid damage if it ends its turn in running water.\nStake to the Heart: If a weapon that deals Piercing damage is driven into the vampire's heart while the vampire has the Incapacitated condition in its resting place, the vampire has the Paralyzed condition until the weapon is removed.\nSunlight: The vampire takes 20 Radiant damage if it starts its turn in sunlight. While in sunlight, it has Disadvantage on attack rolls and ability checks.",
        "damageTypes": [
          "Acid",
          "Piercing",
          "Radiant"
        ]
      }
    ],
    "bonusActions": [
      {
        "name": "Shape-Shift",
        "description": "If the vampire isn't in sunlight or running water, it shape-shifts into a Tiny bat (Speed 5 ft., Fly Speed 30 ft.) or a Medium cloud of mist (Speed 5 ft., Fly Speed 20 ft. [hover]), or it returns to its vampire form. Anything it is wearing transforms with it.\nWhile in bat form, the vampire can't speak. Its game statistics, other than its size and Speed, are unchanged.\nWhile in mist form, the vampire can't take any actions, speak, or manipulate objects. It is weightless and can enter an enemy's space and stop there. If air can pass through a space, the mist can do so, but it can't pass through liquid. It has Resistance to all damage, except the damage it takes from sunlight."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Deathless Strike",
          "description": "The vampire moves up to half its Speed, and it makes one Grave Strike attack."
        }
      ],
      "actionsPerRound": 3
    }
  }
];
