// AUTO-GENERATED by scripts/import-bestiary.ts — DO NOT EDIT BY HAND.
// Source: 5etools-src @ 3c5d9d3175ca (bestiary-xmm.json),
// filtered to entries in the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode

import { Monster } from '../lib/types';

// CR 21 – 30 — 12 monsters
export const MONSTERS_CR_21_30: Monster[] = [
  {
    "id": "ancient-black-dragon",
    "name": "Ancient Black Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Chaotic Evil",
    "armor": {
      "ac": 22
    },
    "hitPoints": 367,
    "hitDice": "21d20 + 147",
    "speed": {
      "walk": 40,
      "fly": 80,
      "swim": 40
    },
    "abilities": {
      "str": 27,
      "dex": 14,
      "con": 25,
      "int": 16,
      "wis": 15,
      "cha": 22
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 26"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 21,
    "proficiencyBonus": 7,
    "xp": 33000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Acid"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Melf's Acid Arrow (level 4 version).",
        "damageTypes": [
          "Acid"
        ]
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +15, reach 15 ft. Hit: 17 (2d8 + 8) Slashing damage plus 9 (2d8) Acid damage.",
        "attackDelivery": "Melee",
        "attackBonus": 15,
        "reach": 15,
        "damageTypes": [
          "Acid",
          "Slashing"
        ],
        "damageDice": "2d8+8",
        "damageAvg": 17
      },
      {
        "name": "Acid Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 22, each creature in a 90-foot-long, 10-foot-wide Line. Failure: 67 (15d8) Acid damage. Success: Half damage.",
        "damageTypes": [
          "Acid"
        ],
        "damageDice": "15d8",
        "damageAvg": 67
      }
    ],
    "environments": [
      "Swamp"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Swim"
    ],
    "attackDamageTypes": [
      "Acid",
      "Slashing",
      "Poison"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "chromatic",
    "savingThrows": {
      "dex": 9,
      "wis": 9
    },
    "skills": {
      "Perception": 16,
      "Stealth": 9
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 21,
      "attackBonus": 13,
      "atWill": [
        "Detect Magic",
        "Fear",
        "Melf's Acid Arrow (level 4 version)"
      ],
      "perDay": {
        "1": [
          "Create Undead",
          "Speak with Dead",
          "Vitriolic Sphere (level 5 version)"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The dragon can breathe air and water."
      },
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Cloud of Insects",
          "description": "Dexterity Saving Throw: DC 21, one creature the dragon can see within 120 feet. Failure: 33 (6d10) Poison damage, and the target has Disadvantage on saving throws to maintain Concentration until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Poison"
          ],
          "damageDice": "6d10",
          "damageAvg": 33
        },
        {
          "name": "Frightful Presence",
          "description": "The dragon uses Spellcasting to cast Fear. The dragon can't take this action again until the start of its next turn."
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "ancient-copper-dragon",
    "name": "Ancient Copper Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Chaotic Good",
    "armor": {
      "ac": 21
    },
    "hitPoints": 367,
    "hitDice": "21d20 + 147",
    "speed": {
      "walk": 40,
      "fly": 80,
      "climb": 40
    },
    "abilities": {
      "str": 27,
      "dex": 12,
      "con": 25,
      "int": 20,
      "wis": 17,
      "cha": 22
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 27"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 21,
    "proficiencyBonus": 7,
    "xp": 33000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Acid"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of (A) Slowing Breath or (B) Spellcasting to cast Mind Spike (level 5 version)."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +15, reach 15 ft. Hit: 19 (2d10 + 8) Slashing damage plus 9 (2d8) Acid damage.",
        "attackDelivery": "Melee",
        "attackBonus": 15,
        "reach": 15,
        "damageTypes": [
          "Acid",
          "Slashing"
        ],
        "damageDice": "2d10+8",
        "damageAvg": 19
      },
      {
        "name": "Acid Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 22, each creature in an 90-foot-long, 10-foot-wide Line. Failure: 63 (14d8) Acid damage. Success: Half damage.",
        "damageTypes": [
          "Acid"
        ],
        "damageDice": "14d8",
        "damageAvg": 63
      },
      {
        "name": "Slowing Breath",
        "description": "Constitution Saving Throw: DC 22, each creature in a 90-foot Cone. Failure: The target can't take Reactions; its Speed is halved; and it can take either an action or a Bonus Action on its turn, not both. This effect lasts until the end of its next turn."
      }
    ],
    "environments": [
      "Hill"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Climb"
    ],
    "attackDamageTypes": [
      "Acid",
      "Slashing",
      "Psychic"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "metallic",
    "savingThrows": {
      "dex": 8,
      "wis": 10
    },
    "skills": {
      "Deception": 13,
      "Perception": 17,
      "Stealth": 8
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 21,
      "atWill": [
        "Detect Magic",
        "Mind Spike (level 5 version)",
        "Minor Illusion",
        "Shapechange (Beast or Humanoid form only, no Temporary Hit Points gained from the spell, and no Concentration or Temporary Hit Points required to maintain the spell)"
      ],
      "perDay": {
        "1": [
          "Greater Restoration",
          "Major Image",
          "Project Image"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Giggling Magic",
          "description": "Charisma Saving Throw: DC 21, one creature the dragon can see within 120 feet. Failure: 31 (9d6) Psychic damage. Until the end of its next turn, the target rolls 1d8 whenever it makes an ability check or attack roll and subtracts the number rolled from the D20 Test. Failure or Success: The dragon can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Psychic"
          ],
          "damageDice": "9d6",
          "damageAvg": 31
        },
        {
          "name": "Mind Jolt",
          "description": "The dragon uses Spellcasting to cast Mind Spike (level 5 version). The dragon can't take this action again until the start of its next turn."
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "lich",
    "name": "Lich",
    "source": "SRD52",
    "size": "Medium",
    "type": "Undead",
    "alignment": "Neutral Evil",
    "armor": {
      "ac": 20
    },
    "hitPoints": 315,
    "hitDice": "42d8 + 126",
    "speed": {
      "walk": 30
    },
    "abilities": {
      "str": 11,
      "dex": 16,
      "con": 16,
      "int": 21,
      "wis": 14,
      "cha": 16
    },
    "senses": [
      "Truesight 120 ft.",
      "passive Perception 19"
    ],
    "languages": [
      "all"
    ],
    "challengeRating": 21,
    "proficiencyBonus": 7,
    "xp": 33000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Cold",
      "Lightning"
    ],
    "damageImmunities": [
      "Necrotic",
      "Poison"
    ],
    "conditionImmunities": [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The lich makes three attacks, using Eldritch Burst or Paralyzing Touch in any combination."
      },
      {
        "name": "Eldritch Burst",
        "description": "Melee or Ranged Attack Roll: +12, reach 5 ft. or range 120 ft. Hit: 31 (4d12 + 5) Force damage.",
        "attackDelivery": "Melee",
        "attackBonus": 12,
        "reach": 5,
        "range": 120,
        "damageTypes": [
          "Force"
        ],
        "damageDice": "4d12+5",
        "damageAvg": 31
      },
      {
        "name": "Paralyzing Touch",
        "description": "Melee Attack Roll: +12, reach 5 ft. Hit: 15 (3d6 + 5) Cold damage, and the target has the Paralyzed condition until the start of the lich's next turn.",
        "attackDelivery": "Melee",
        "attackBonus": 12,
        "reach": 5,
        "damageTypes": [
          "Cold"
        ],
        "damageDice": "3d6+5",
        "damageAvg": 15
      }
    ],
    "environments": [
      "Any"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk"
    ],
    "attackDamageTypes": [
      "Force",
      "Cold",
      "Necrotic"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack"
    ],
    "subtype": "wizard",
    "savingThrows": {
      "dex": 10,
      "con": 10,
      "int": 12,
      "wis": 9
    },
    "skills": {
      "Arcana": 19,
      "History": 12,
      "Insight": 9,
      "Perception": 9
    },
    "spellcasting": {
      "ability": "int",
      "dc": 20,
      "atWill": [
        "Detect Magic",
        "Detect Thoughts",
        "Dispel Magic",
        "Fireball (level 5 version)",
        "Invisibility",
        "Lightning Bolt (level 5 version)",
        "Mage Hand",
        "Prestidigitation"
      ],
      "perDay": {
        "1": [
          "Chain Lightning",
          "Finger of Death",
          "Power Word Kill",
          "Scrying"
        ],
        "2": [
          "Animate Dead",
          "Dimension Door",
          "Plane Shift"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the lich fails a saving throw, it can choose to succeed instead."
      },
      {
        "name": "Spirit Jar",
        "description": "If destroyed, the lich reforms in 1d10 days if it has a spirit jar, reviving with all its Hit Points. The new body appears in an unoccupied space within the lich's lair."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Deathly Teleport",
          "description": "The lich teleports up to 60 feet to an unoccupied space it can see, and each creature within 10 feet of the space it left takes 11 (2d10) Necrotic damage.",
          "damageTypes": [
            "Necrotic"
          ],
          "damageDice": "2d10",
          "damageAvg": 11
        },
        {
          "name": "Disrupt Life",
          "description": "Constitution Saving Throw: DC 20, each creature that isn't an Undead in a 20-foot Emanation originating from the lich. Failure: 31 (9d6) Necrotic damage. Success: Half damage. Failure or Success: The lich can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Necrotic"
          ],
          "damageDice": "9d6",
          "damageAvg": 31
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "solar",
    "name": "Solar",
    "source": "SRD52",
    "size": "Large",
    "type": "Celestial",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 21
    },
    "hitPoints": 297,
    "hitDice": "22d10 + 176",
    "speed": {
      "walk": 50,
      "fly": 150,
      "hover": true
    },
    "abilities": {
      "str": 26,
      "dex": 22,
      "con": 26,
      "int": 25,
      "wis": 25,
      "cha": 30
    },
    "senses": [
      "Truesight 120 ft.",
      "passive Perception 24"
    ],
    "languages": [
      "all; telepathy 120 ft."
    ],
    "challengeRating": 21,
    "proficiencyBonus": 7,
    "xp": 33000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Poison",
      "Radiant"
    ],
    "conditionImmunities": [
      "Charmed",
      "Exhaustion",
      "Frightened",
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The solar makes two Flying Sword attacks. It can replace one attack with a use of Slaying Bow."
      },
      {
        "name": "Flying Sword",
        "description": "Melee or Ranged Attack Roll: +15, reach 10 ft. or range 120 ft. Hit: 22 (4d6 + 8) Slashing damage plus 36 (8d8) Radiant damage. Hit or Miss: The sword magically returns to the solar's hand or hovers within 5 feet of the solar immediately after a ranged attack.",
        "attackDelivery": "Melee",
        "attackBonus": 15,
        "reach": 10,
        "range": 120,
        "damageTypes": [
          "Radiant",
          "Slashing"
        ],
        "damageDice": "4d6+8",
        "damageAvg": 22
      },
      {
        "name": "Slaying Bow",
        "description": "Dexterity Saving Throw: DC 21, one creature the solar can see within 600 feet. Failure: If the creature has 100 Hit Points or fewer, it dies. It otherwise takes 24 (4d8 + 6) Piercing damage plus 36 (8d8) Radiant damage.",
        "damageTypes": [
          "Piercing",
          "Radiant"
        ],
        "damageDice": "4d8+6",
        "damageAvg": 24
      }
    ],
    "environments": [
      "Planar"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Hover"
    ],
    "attackDamageTypes": [
      "Radiant",
      "Slashing",
      "Piercing"
    ],
    "attackDeliveryModes": [
      "Melee",
      "Ranged"
    ],
    "tags": [
      "multiattack",
      "magic resistance",
      "flyer"
    ],
    "subtype": "angel",
    "skills": {
      "Perception": 14
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 25,
      "atWill": [
        "Detect Evil and Good"
      ],
      "perDay": {
        "1": [
          "Commune",
          "Control Weather",
          "Dispel Evil and Good",
          "Resurrection"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Divine Awareness",
        "description": "The solar knows if it hears a lie."
      },
      {
        "name": "Exalted Restoration",
        "description": "If the solar dies outside Mount Celestia, its body disappears, and it gains a new body instantly, reviving with all its Hit Points somewhere in Mount Celestia."
      },
      {
        "name": "Legendary Resistance (4/Day)",
        "description": "If the solar fails a saving throw, it can choose to succeed instead."
      },
      {
        "name": "Magic Resistance",
        "description": "The solar has Advantage on saving throws against spells and other magical effects."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Blinding Gaze",
          "description": "Constitution Saving Throw: DC 25, one creature the solar can see within 120 feet. Failure: The target has the Blinded condition for 1 minute. Failure or Success: The solar can't take this action again until the start of its next turn."
        },
        {
          "name": "Radiant Teleport",
          "description": "The solar teleports up to 60 feet to an unoccupied space it can see. Dexterity Saving Throw: DC 25, each creature in a 10-foot Emanation originating from the solar at its destination space. Failure: 11 (2d10) Radiant damage. Success: Half damage.",
          "damageTypes": [
            "Radiant"
          ],
          "damageDice": "2d10",
          "damageAvg": 11
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "ancient-bronze-dragon",
    "name": "Ancient Bronze Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 22
    },
    "hitPoints": 444,
    "hitDice": "24d20 + 192",
    "speed": {
      "walk": 40,
      "fly": 80,
      "swim": 40
    },
    "abilities": {
      "str": 29,
      "dex": 10,
      "con": 27,
      "int": 18,
      "wis": 17,
      "cha": 25
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 27"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 22,
    "proficiencyBonus": 7,
    "xp": 41000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Lightning"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of (A) Repulsion Breath or (B) Spellcasting to cast Guiding Bolt (level 2 version)."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +16, reach 15 ft. Hit: 18 (2d8 + 9) Slashing damage plus 9 (2d8) Lightning damage.",
        "attackDelivery": "Melee",
        "attackBonus": 16,
        "reach": 15,
        "damageTypes": [
          "Lightning",
          "Slashing"
        ],
        "damageDice": "2d8+9",
        "damageAvg": 18
      },
      {
        "name": "Lightning Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 23, each creature in a 120-foot-long, 10-foot-wide Line. Failure: 82 (15d10) Lightning damage. Success: Half damage.",
        "damageTypes": [
          "Lightning"
        ],
        "damageDice": "15d10",
        "damageAvg": 82
      },
      {
        "name": "Repulsion Breath",
        "description": "Strength Saving Throw: DC 23, each creature in a 30-foot Cone. Failure: The target is pushed up to 60 feet straight away from the dragon and has the Prone condition."
      }
    ],
    "environments": [
      "Coastal"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Swim"
    ],
    "attackDamageTypes": [
      "Lightning",
      "Slashing",
      "Thunder"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "metallic",
    "savingThrows": {
      "dex": 7,
      "wis": 10
    },
    "skills": {
      "Insight": 10,
      "Perception": 17,
      "Stealth": 7
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 22,
      "attackBonus": 14,
      "atWill": [
        "Detect Magic",
        "Guiding Bolt (level 2 version)",
        "Shapechange (Beast or Humanoid form only, no Temporary Hit Points gained from the spell, and no Concentration or Temporary Hit Points required to maintain the spell)",
        "Speak with Animals",
        "Thaumaturgy"
      ],
      "perDay": {
        "1": [
          "Detect Thoughts",
          "Control Water",
          "Scrying",
          "Water Breathing"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The dragon can breathe air and water."
      },
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Guiding Light",
          "description": "The dragon uses Spellcasting to cast Guiding Bolt (level 2 version)."
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        },
        {
          "name": "Thunderclap",
          "description": "Constitution Saving Throw: DC 22, each creature in a 20-foot-radius Sphere centered on a point the dragon can see within 120 feet. Failure: 13 (3d8) Thunder damage, and the target has the Deafened condition until the end of its next turn.",
          "damageTypes": [
            "Thunder"
          ],
          "damageDice": "3d8",
          "damageAvg": 13
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "ancient-green-dragon",
    "name": "Ancient Green Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 21
    },
    "hitPoints": 402,
    "hitDice": "23d20 + 161",
    "speed": {
      "walk": 40,
      "fly": 80,
      "swim": 40
    },
    "abilities": {
      "str": 27,
      "dex": 12,
      "con": 25,
      "int": 20,
      "wis": 17,
      "cha": 22
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 27"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 22,
    "proficiencyBonus": 7,
    "xp": 41000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Poison"
    ],
    "conditionImmunities": [
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Mind Spike (level 5 version)."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +15, reach 15 ft. Hit: 17 (2d8 + 8) Slashing damage plus 10 (3d6) Poison damage.",
        "attackDelivery": "Melee",
        "attackBonus": 15,
        "reach": 15,
        "damageTypes": [
          "Poison",
          "Slashing"
        ],
        "damageDice": "2d8+8",
        "damageAvg": 17
      },
      {
        "name": "Poison Breath (Recharge 5–6)",
        "description": "Constitution Saving Throw: DC 22, each creature in a 90-foot Cone. Failure: 77 (22d6) Poison damage. Success: Half damage.",
        "damageTypes": [
          "Poison"
        ],
        "damageDice": "22d6",
        "damageAvg": 77
      }
    ],
    "environments": [
      "Forest"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Swim"
    ],
    "attackDamageTypes": [
      "Poison",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "chromatic",
    "savingThrows": {
      "dex": 8,
      "wis": 10
    },
    "skills": {
      "Deception": 13,
      "Perception": 17,
      "Persuasion": 13,
      "Stealth": 8
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 21,
      "atWill": [
        "Detect Magic",
        "Mind Spike (level 5 version)"
      ],
      "perDay": {
        "1": [
          "Geas",
          "Modify Memory"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The dragon can breathe air and water."
      },
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Mind Invasion",
          "description": "The dragon uses Spellcasting to cast Mind Spike (level 5 version)."
        },
        {
          "name": "Noxious Miasma",
          "description": "Constitution Saving Throw: DC 21, each creature in a 30-foot-radius Sphere centered on a point the dragon can see within 90 feet. Failure: 17 (5d6) Poison damage, and the target takes a -2 penalty to AC until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Poison"
          ],
          "damageDice": "5d6",
          "damageAvg": 17
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "ancient-blue-dragon",
    "name": "Ancient Blue Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Lawful Evil",
    "armor": {
      "ac": 22
    },
    "hitPoints": 481,
    "hitDice": "26d20 + 208",
    "speed": {
      "walk": 40,
      "fly": 80,
      "burrow": 40
    },
    "abilities": {
      "str": 29,
      "dex": 10,
      "con": 27,
      "int": 18,
      "wis": 17,
      "cha": 25
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 27"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 23,
    "proficiencyBonus": 7,
    "xp": 50000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Lightning"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Shatter (level 3 version)."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +16, reach 15 ft. Hit: 18 (2d8 + 9) Slashing damage plus 11 (2d10) Lightning damage.",
        "attackDelivery": "Melee",
        "attackBonus": 16,
        "reach": 15,
        "damageTypes": [
          "Lightning",
          "Slashing"
        ],
        "damageDice": "2d8+9",
        "damageAvg": 18
      },
      {
        "name": "Lightning Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 23, each creature in a 120-foot-long, 10-foot-wide Line. Failure: 88 (16d10) Lightning damage. Success: Half damage.",
        "damageTypes": [
          "Lightning"
        ],
        "damageDice": "16d10",
        "damageAvg": 88
      }
    ],
    "environments": [
      "Coastal",
      "Desert"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Burrow"
    ],
    "attackDamageTypes": [
      "Lightning",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "chromatic",
    "savingThrows": {
      "dex": 7,
      "wis": 10
    },
    "skills": {
      "Perception": 17,
      "Stealth": 7
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 22,
      "atWill": [
        "Detect Magic",
        "Invisibility",
        "Mage Hand",
        "Shatter (level 3 version)"
      ],
      "perDay": {
        "1": [
          "Scrying",
          "Sending"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Cloaked Flight",
          "description": "The dragon uses Spellcasting to cast Invisibility on itself, and it can fly up to half its Fly Speed. The dragon can't take this action again until the start of its next turn."
        },
        {
          "name": "Sonic Boom",
          "description": "The dragon uses Spellcasting to cast Shatter (level 3 version). The dragon can't take this action again until the start of its next turn."
        },
        {
          "name": "Tail Swipe",
          "description": "The dragon makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "ancient-silver-dragon",
    "name": "Ancient Silver Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 22
    },
    "hitPoints": 468,
    "hitDice": "24d20 + 216",
    "speed": {
      "walk": 40,
      "fly": 80
    },
    "abilities": {
      "str": 30,
      "dex": 10,
      "con": 29,
      "int": 18,
      "wis": 15,
      "cha": 26
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 26"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 23,
    "proficiencyBonus": 7,
    "xp": 50000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Cold"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of (A) Paralyzing Breath or (B) Spellcasting to cast Ice Knife (level 2 version)."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +17, reach 15 ft. Hit: 19 (2d8 + 10) Slashing damage plus 9 (2d8) Cold damage.",
        "attackDelivery": "Melee",
        "attackBonus": 17,
        "reach": 15,
        "damageTypes": [
          "Cold",
          "Slashing"
        ],
        "damageDice": "2d8+10",
        "damageAvg": 19
      },
      {
        "name": "Cold Breath (Recharge 5–6)",
        "description": "Constitution Saving Throw: DC 24, each creature in a 90-foot Cone. Failure: 67 (15d8) Cold damage. Success: Half damage.",
        "damageTypes": [
          "Cold"
        ],
        "damageDice": "15d8",
        "damageAvg": 67
      },
      {
        "name": "Paralyzing Breath",
        "description": "Constitution Saving Throw: DC 24, each creature in a 90-foot Cone. Failure: The target has the Incapacitated condition until the end of its next turn, when it repeats the save. Failure: The target has the Paralyzed condition, and it repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."
      }
    ],
    "environments": [
      "Mountain",
      "Urban"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly"
    ],
    "attackDamageTypes": [
      "Cold",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "metallic",
    "savingThrows": {
      "dex": 7,
      "wis": 9
    },
    "skills": {
      "History": 11,
      "Perception": 16,
      "Stealth": 7
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 23,
      "attackBonus": 15,
      "atWill": [
        "Detect Magic",
        "Hold Monster",
        "Ice Knife (level 2 version)",
        "Shapechange (Beast or Humanoid form only, no Temporary Hit Points gained from the spell, and no Concentration or Temporary Hit Points required to maintain the spell)"
      ],
      "perDay": {
        "1": [
          "Control Weather",
          "Ice Storm (level 7 version)",
          "Teleport",
          "Zone of Truth"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Chill",
          "description": "The dragon uses Spellcasting to cast Hold Monster. The dragon can't take this action again until the start of its next turn."
        },
        {
          "name": "Cold Gale",
          "description": "Dexterity Saving Throw: DC 23, each creature in a 60-foot-long, 10-foot-wide Line. Failure: 14 (4d6) Cold damage, and the target is pushed up to 30 feet straight away from the dragon. Success: Half damage only. Failure or Success: The dragon can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Cold"
          ],
          "damageDice": "4d6",
          "damageAvg": 14
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "kraken",
    "name": "Kraken",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Monstrosity",
    "alignment": "Chaotic Evil",
    "armor": {
      "ac": 18
    },
    "hitPoints": 481,
    "hitDice": "26d20 + 208",
    "speed": {
      "walk": 30,
      "swim": 120
    },
    "abilities": {
      "str": 30,
      "dex": 11,
      "con": 26,
      "int": 22,
      "wis": 18,
      "cha": 20
    },
    "senses": [
      "Truesight 120 ft.",
      "passive Perception 21"
    ],
    "languages": [
      "understands Abyssal",
      "Celestial",
      "Infernal",
      "and Primordial but can't speak; telepathy 120 ft."
    ],
    "challengeRating": 23,
    "proficiencyBonus": 7,
    "xp": 50000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Cold",
      "Lightning"
    ],
    "conditionImmunities": [
      "Frightened",
      "Grappled",
      "Paralyzed",
      "Restrained"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The kraken makes two Tentacle attacks and uses Fling, Lightning Strike, or Swallow.",
        "damageTypes": [
          "Lightning"
        ]
      },
      {
        "name": "Tentacle",
        "description": "Melee Attack Roll: +17, reach 30 ft. Hit: 24 (4d6 + 10) Bludgeoning damage. The target has the Grappled condition (escape DC 20) from one of ten tentacles, and it has the Restrained condition until the grapple ends.",
        "attackDelivery": "Melee",
        "attackBonus": 17,
        "reach": 30,
        "damageTypes": [
          "Bludgeoning"
        ],
        "damageDice": "4d6+10",
        "damageAvg": 24
      },
      {
        "name": "Fling",
        "description": "The kraken throws a Large or smaller creature Grappled by it to a space it can see within 60 feet of itself that isn't in the air. Dexterity Saving Throw: DC 25, the creature thrown and each creature in the destination space. Failure: 18 (4d8) Bludgeoning damage, and the target has the Prone condition. Success: Half damage only.",
        "damageTypes": [
          "Bludgeoning"
        ],
        "damageDice": "4d8",
        "damageAvg": 18
      },
      {
        "name": "Lightning Strike",
        "description": "Dexterity Saving Throw: DC 23, one creature the kraken can see within 120 feet. Failure: 33 (6d10) Lightning damage. Success: Half damage.",
        "damageTypes": [
          "Lightning"
        ],
        "damageDice": "6d10",
        "damageAvg": 33
      },
      {
        "name": "Swallow",
        "description": "Dexterity Saving Throw: DC 25, one creature Grappled by the kraken (it can have up to four creatures swallowed at a time). Failure: 23 (3d8 + 10) Piercing damage. If the target is Large or smaller, it is swallowed and no longer Grappled. A swallowed creature has the Restrained condition, has Total Cover against attacks and other effects outside the kraken, and takes 24 (7d6) Acid damage at the start of each of its turns.\nIf the kraken takes 50 damage or more on a single turn from a creature inside it, the kraken must succeed on a DC 25 Constitution saving throw at the end of that turn or regurgitate all swallowed creatures, each of which falls in a space within 10 feet of the kraken with the Prone condition. If the kraken dies, any swallowed creature no longer has the Restrained condition and can escape from the corpse using 15 feet of movement, exiting Prone.",
        "damageTypes": [
          "Acid",
          "Piercing"
        ],
        "damageDice": "3d8+10",
        "damageAvg": 23
      }
    ],
    "environments": [
      "Underwater"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Swim"
    ],
    "attackDamageTypes": [
      "Lightning",
      "Bludgeoning",
      "Acid",
      "Piercing",
      "Poison"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "swallow",
      "grappler"
    ],
    "subtype": "titan",
    "savingThrows": {
      "str": 17,
      "dex": 7,
      "con": 15,
      "wis": 11
    },
    "skills": {
      "History": 13,
      "Perception": 11
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The kraken can breathe air and water."
      },
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the kraken fails a saving throw, it can choose to succeed instead."
      },
      {
        "name": "Siege Monster",
        "description": "The kraken deals double damage to objects and structures."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Storm Bolt",
          "description": "The kraken uses Lightning Strike.",
          "damageTypes": [
            "Lightning"
          ]
        },
        {
          "name": "Toxic Ink",
          "description": "Constitution Saving Throw: DC 23, each creature in a 15-foot Emanation originating from the kraken while it is underwater. Failure: The target has the Blinded and Poisoned conditions until the end of the kraken's next turn. The kraken then moves up to its Speed. Failure or Success: The kraken can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Poison"
          ]
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "ancient-gold-dragon",
    "name": "Ancient Gold Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Lawful Good",
    "armor": {
      "ac": 22
    },
    "hitPoints": 546,
    "hitDice": "28d20 + 252",
    "speed": {
      "walk": 40,
      "fly": 80,
      "swim": 40
    },
    "abilities": {
      "str": 30,
      "dex": 14,
      "con": 29,
      "int": 18,
      "wis": 17,
      "cha": 28
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 27"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 24,
    "proficiencyBonus": 7,
    "xp": 62000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of (A) Spellcasting to cast Guiding Bolt (level 4 version) or (B) Weakening Breath."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +17 to hit, reach 15 ft. Hit: 19 (2d8 + 10) Slashing damage plus 9 (2d8) Fire damage.",
        "attackDelivery": "Melee",
        "attackBonus": 17,
        "reach": 15,
        "damageTypes": [
          "Fire",
          "Slashing"
        ],
        "damageDice": "2d8+10",
        "damageAvg": 19
      },
      {
        "name": "Fire Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 24, each creature in a 90-foot Cone. Failure: 71 (13d10) Fire damage. Success: Half damage.",
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "13d10",
        "damageAvg": 71
      },
      {
        "name": "Weakening Breath",
        "description": "Strength Saving Throw: DC 24, each creature that isn't currently affected by this breath in a 90-foot Cone. Failure: The target has Disadvantage on Strength-based D20 Tests and subtracts 5 (1d10) from its damage rolls. It repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically.",
        "damageDice": "1d10",
        "damageAvg": 5
      }
    ],
    "environments": [
      "Forest",
      "Grassland"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Swim"
    ],
    "attackDamageTypes": [
      "Fire",
      "Slashing",
      "Force"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "metallic",
    "savingThrows": {
      "dex": 9,
      "wis": 10
    },
    "skills": {
      "Insight": 10,
      "Perception": 17,
      "Persuasion": 16,
      "Stealth": 9
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 24,
      "attackBonus": 16,
      "atWill": [
        "Detect Magic",
        "Guiding Bolt (level 4 version)",
        "Shapechange (Beast or Humanoid form only, no Temporary Hit Points gained from the spell, and no Concentration or Temporary Hit Points required to maintain the spell)"
      ],
      "perDay": {
        "1": [
          "Flame Strike (level 6 version)",
          "Word of Recall",
          "Zone of Truth"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Amphibious",
        "description": "The dragon can breathe air and water."
      },
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Banish",
          "description": "Charisma Saving Throw: DC 24, one creature the dragon can see within 120 feet. Failure: 24 (7d6) Force damage, and the target has the Incapacitated condition and is transported to a harmless demiplane until the start of the dragon's next turn, at which point it reappears in an unoccupied space of the dragon's choice within 120 feet of the dragon. Failure or Success: The dragon can't take this action again until the start of its next turn.",
          "damageTypes": [
            "Force"
          ],
          "damageDice": "7d6",
          "damageAvg": 24
        },
        {
          "name": "Guiding Light",
          "description": "The dragon uses Spellcasting to cast Guiding Bolt (level 4 version)."
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "ancient-red-dragon",
    "name": "Ancient Red Dragon",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Dragon",
    "alignment": "Chaotic Evil",
    "armor": {
      "ac": 22
    },
    "hitPoints": 507,
    "hitDice": "26d20 + 234",
    "speed": {
      "walk": 40,
      "fly": 80,
      "climb": 40
    },
    "abilities": {
      "str": 30,
      "dex": 10,
      "con": 29,
      "int": 18,
      "wis": 15,
      "cha": 27
    },
    "senses": [
      "Blindsight 60 ft.",
      "Darkvision 120 ft.",
      "passive Perception 26"
    ],
    "languages": [
      "Common",
      "Draconic"
    ],
    "challengeRating": 24,
    "proficiencyBonus": 7,
    "xp": 62000,
    "damageVulnerabilities": [],
    "damageResistances": [],
    "damageImmunities": [
      "Fire"
    ],
    "conditionImmunities": [],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Scorching Ray (level 3 version)."
      },
      {
        "name": "Rend",
        "description": "Melee Attack Roll: +17, reach 15 ft. Hit: 19 (2d8 + 10) Slashing damage plus 10 (3d6) Fire damage.",
        "attackDelivery": "Melee",
        "attackBonus": 17,
        "reach": 15,
        "damageTypes": [
          "Fire",
          "Slashing"
        ],
        "damageDice": "2d8+10",
        "damageAvg": 19
      },
      {
        "name": "Fire Breath (Recharge 5–6)",
        "description": "Dexterity Saving Throw: DC 24, each creature in a 90-foot Cone. Failure: 91 (26d6) Fire damage. Success: Half damage.",
        "damageTypes": [
          "Fire"
        ],
        "damageDice": "26d6",
        "damageAvg": 91
      }
    ],
    "environments": [
      "Hill",
      "Mountain"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": true,
    "hasSpellcasting": true,
    "movementModes": [
      "Walk",
      "Fly",
      "Climb"
    ],
    "attackDamageTypes": [
      "Fire",
      "Slashing"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "breath weapon",
      "flyer"
    ],
    "subtype": "chromatic",
    "savingThrows": {
      "dex": 7,
      "wis": 9
    },
    "skills": {
      "Perception": 16,
      "Stealth": 7
    },
    "spellcasting": {
      "ability": "cha",
      "dc": 23,
      "attackBonus": 15,
      "atWill": [
        "Command (level 2 version)",
        "Detect Magic",
        "Scorching Ray (level 3 version)"
      ],
      "perDay": {
        "1": [
          "Fireball (level 6 version)",
          "Scrying"
        ]
      }
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (4/Day, or 5/Day in Lair)",
        "description": "If the dragon fails a saving throw, it can choose to succeed instead."
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Commanding Presence",
          "description": "The dragon uses Spellcasting to cast Command (level 2 version). The dragon can't take this action again until the start of its next turn."
        },
        {
          "name": "Fiery Rays",
          "description": "The dragon uses Spellcasting to cast Scorching Ray (level 3 version). The dragon can't take this action again until the start of its next turn."
        },
        {
          "name": "Pounce",
          "description": "The dragon moves up to half its Speed, and it makes one Rend attack."
        }
      ],
      "actionsPerRound": 3
    }
  },
  {
    "id": "tarrasque",
    "name": "Tarrasque",
    "source": "SRD52",
    "size": "Gargantuan",
    "type": "Monstrosity",
    "alignment": "Unaligned",
    "armor": {
      "ac": 25
    },
    "hitPoints": 697,
    "hitDice": "34d20 + 340",
    "speed": {
      "walk": 60,
      "burrow": 40,
      "climb": 60
    },
    "abilities": {
      "str": 30,
      "dex": 11,
      "con": 30,
      "int": 3,
      "wis": 11,
      "cha": 11
    },
    "senses": [
      "Blindsight 120 ft.",
      "passive Perception 19"
    ],
    "languages": [],
    "challengeRating": 30,
    "proficiencyBonus": 9,
    "xp": 155000,
    "damageVulnerabilities": [],
    "damageResistances": [
      "Bludgeoning",
      "Piercing",
      "Slashing"
    ],
    "damageImmunities": [
      "Fire",
      "Poison"
    ],
    "conditionImmunities": [
      "Charmed",
      "Deafened",
      "Frightened",
      "Paralyzed",
      "Poisoned"
    ],
    "actions": [
      {
        "name": "Multiattack",
        "description": "The tarrasque makes one Bite attack and three other attacks, using Claw or Tail in any combination."
      },
      {
        "name": "Bite",
        "description": "Melee Attack Roll: +19, reach 15 ft. Hit: 36 (4d12 + 10) Piercing damage, and the target has the Grappled condition (escape DC 20). Until the grapple ends, the target has the Restrained condition and can't teleport.",
        "attackDelivery": "Melee",
        "attackBonus": 19,
        "reach": 15,
        "damageTypes": [
          "Piercing"
        ],
        "damageDice": "4d12+10",
        "damageAvg": 36
      },
      {
        "name": "Claw",
        "description": "Melee Attack Roll: +19, reach 15 ft. Hit: 28 (4d8 + 10) Slashing damage.",
        "attackDelivery": "Melee",
        "attackBonus": 19,
        "reach": 15,
        "damageTypes": [
          "Slashing"
        ],
        "damageDice": "4d8+10",
        "damageAvg": 28
      },
      {
        "name": "Tail",
        "description": "Melee Attack Roll: +19, reach 30 ft. Hit: 23 (3d8 + 10) Bludgeoning damage. If the target is a Huge or smaller creature, it has the Prone condition.",
        "attackDelivery": "Melee",
        "attackBonus": 19,
        "reach": 30,
        "damageTypes": [
          "Bludgeoning"
        ],
        "damageDice": "3d8+10",
        "damageAvg": 23
      },
      {
        "name": "Thunderous Bellow (Recharge 5–6)",
        "description": "Constitution Saving Throw: DC 27, each creature and each object that isn't being worn or carried in a 150-foot Cone. Failure: 78 (12d12) Thunder damage, and the target has the Deafened and Frightened conditions until the end of its next turn. Success: Half damage only.",
        "damageTypes": [
          "Thunder"
        ],
        "damageDice": "12d12",
        "damageAvg": 78
      }
    ],
    "environments": [
      "Urban"
    ],
    "isLegendary": true,
    "isMythic": false,
    "hasLair": false,
    "hasSpellcasting": false,
    "movementModes": [
      "Walk",
      "Burrow",
      "Climb"
    ],
    "attackDamageTypes": [
      "Piercing",
      "Slashing",
      "Bludgeoning",
      "Thunder",
      "Acid"
    ],
    "attackDeliveryModes": [
      "Melee"
    ],
    "tags": [
      "multiattack",
      "swallow",
      "frightening",
      "grappler",
      "magic resistance"
    ],
    "subtype": "titan",
    "savingThrows": {
      "dex": 9,
      "int": 5,
      "wis": 9,
      "cha": 9
    },
    "skills": {
      "Perception": 9
    },
    "specialAbilities": [
      {
        "name": "Legendary Resistance (6/Day)",
        "description": "If the tarrasque fails a saving throw, it can choose to succeed instead."
      },
      {
        "name": "Magic Resistance",
        "description": "The tarrasque has Advantage on saving throws against spells and other magical effects."
      },
      {
        "name": "Reflective Carapace",
        "description": "If the tarrasque is targeted by a Magic Missile spell or a spell that requires a ranged attack roll, roll 1d6. On a 1-5, the tarrasque is unaffected. On a 6, the tarrasque is unaffected and reflects the spell, turning the caster into the target.",
        "attackDelivery": "Ranged"
      },
      {
        "name": "Siege Monster",
        "description": "The tarrasque deals double damage to objects and structures."
      }
    ],
    "bonusActions": [
      {
        "name": "Swallow",
        "description": "Strength Saving Throw: DC 27, one Large or smaller creature Grappled by the tarrasque (it can have up to six creatures swallowed at a time). Failure: The target is swallowed, and the Grappled condition ends. A swallowed creature has the Blinded and Restrained conditions and can't teleport, it has Total Cover against attacks and other effects outside the tarrasque, and it takes 56 (16d6) Acid damage at the start of each of the tarrasque's turns.\nIf the tarrasque takes 60 damage or more on a single turn from a creature inside it, the tarrasque must succeed on a DC 20 Constitution saving throw at the end of that turn or regurgitate all swallowed creatures, each of which falls in a space within 10 feet of the tarrasque and has the Prone condition. If the tarrasque dies, any swallowed creature no longer has the Restrained condition and can escape from the corpse using 20 feet of movement, exiting Prone.",
        "damageTypes": [
          "Acid"
        ],
        "damageDice": "16d6",
        "damageAvg": 56
      }
    ],
    "legendary": {
      "description": "The creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The creature regains spent legendary actions at the start of its turn.",
      "actions": [
        {
          "name": "Onslaught",
          "description": "The tarrasque moves up to half its Speed, and it makes one Claw or Tail attack."
        },
        {
          "name": "World-Shaking Movement",
          "description": "The tarrasque moves up to its Speed. At the end of this movement, the tarrasque creates an instantaneous shock wave in a 60-foot Emanation originating from itself. Creatures in that area lose Concentration and, if Medium or smaller, have the Prone condition. The tarrasque can't take this action again until the start of its next turn."
        }
      ],
      "actionsPerRound": 3
    }
  }
];
