// AUTO-GENERATED by scripts/import-srd-content.ts — DO NOT EDIT BY HAND.
// Source: https://github.com/oldmanumby/dnd.srd.5.2.1 @ af537072cc95,
// transcribed from the System Reference Document 5.2.1.
// SRD 5.2.1 content © Wizards of the Coast LLC, licensed under the
// Creative Commons Attribution 4.0 International License (CC-BY-4.0):
// https://creativecommons.org/licenses/by/4.0/legalcode

import type { SrdReferenceContentMeta } from '../lib/srd-content-types';

export const REFERENCE_CONTENT_META: SrdReferenceContentMeta = {
  rules: 200,
  classes: 24,
  equipment: 182,
  source: 'SRD 5.2.1',
  license: 'CC-BY-4.0',
  sourceRepository: 'oldmanumby/dnd.srd.5.2.1',
  sourceCommit: 'af537072cc95f362544c71ad14d56046a9aa065a',
};
