// ─── Spell Data & Search ─────────────────────────────────────────
// The spell arrays are AUTO-GENERATED by scripts/import-spells.ts into
// the spells-l*.ts band files (SRD 5.2.1, CC-BY-4.0). This module owns
// the Spell type and the search/filter helpers, and aggregates the bands.

import { SPELLS_L0_1 } from './spells-l0-1';
import { SPELLS_L2_3 } from './spells-l2-3';
import { SPELLS_L4_5 } from './spells-l4-5';
import { SPELLS_L6_9 } from './spells-l6-9';

export type SpellSchool = 'Abjuration' | 'Conjuration' | 'Divination' | 'Enchantment' | 'Evocation' | 'Illusion' | 'Necromancy' | 'Transmutation';

export interface Spell {
  id: string;
  name: string;
  level: number;
  school: SpellSchool;
  castingTime: string;
  range: string;
  area?: string;
  components: string;
  duration: string;
  concentration: boolean;
  ritual: boolean;
  saveType?: string;
  attackType?: 'melee' | 'ranged';
  damageType?: string;
  effectSummary: string;
  upcast?: string;
  classes: string[];
  description: string;
  source: string;
}

export const SRD_SPELLS: Spell[] = [
  ...SPELLS_L0_1,
  ...SPELLS_L2_3,
  ...SPELLS_L4_5,
  ...SPELLS_L6_9,
];

// ─── Search ──────────────────────────────────────────────────────

export function searchSpells(query: string, spells: Spell[] = SRD_SPELLS): Spell[] {
  const q = query.toLowerCase().trim();
  if (!q) return spells;
  return spells.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.school.toLowerCase().includes(q) ||
    s.classes.some(c => c.toLowerCase().includes(q)) ||
    s.effectSummary.toLowerCase().includes(q) ||
    (s.damageType && s.damageType.toLowerCase().includes(q))
  );
}

export function filterSpells(spells: Spell[], filters: {
  level?: number;
  school?: SpellSchool;
  className?: string;
  concentration?: boolean;
  ritual?: boolean;
  castingTime?: string;
}): Spell[] {
  let result = spells;
  if (filters.level !== undefined) result = result.filter(s => s.level === filters.level);
  if (filters.school) result = result.filter(s => s.school === filters.school);
  if (filters.className) result = result.filter(s => s.classes.some(c => c.toLowerCase() === filters.className!.toLowerCase()));
  if (filters.concentration !== undefined) result = result.filter(s => s.concentration === filters.concentration);
  if (filters.ritual !== undefined) result = result.filter(s => s.ritual === filters.ritual);
  if (filters.castingTime) result = result.filter(s => s.castingTime.toLowerCase() === filters.castingTime!.toLowerCase());
  return result;
}

export function levelLabel(level: number): string {
  if (level === 0) return 'Cantrip';
  if (level === 1) return '1st';
  if (level === 2) return '2nd';
  if (level === 3) return '3rd';
  return `${level}th`;
}
